### ISSUE TITLE
Cap.04 - Estrutura de Dados: Objeto e Array

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#10]
Tradução do arquivo [04-estrutura-de-dados.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/04-estruturas-de-dados.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/04_data.html)

**Comment by SauloSilva** [comment]
@ericdouglas e @fdaciuk como estamos no tradução deste capitulo, caso esteja parada posso continuar?

**Comment by fdaciuk** [comment]
@SauloSilva, estou fazendo, mas a passos beeem lentos =)

**Comment by SauloSilva** [comment]
@fdaciuk ok :D

**Comment by vbesseler** [comment]
Opa, beleza galera?

Algum update na tradução do capitulo 4? Não manjo muito de JavaScript ainda, mas posso ir lendo o capitulo em inglês e traduzindo pra português caso ninguém esteja trabalhando nisso.

**Comment by joaostein** [comment]
@ericdouglas @gabrielfgularte @SauloSilva -- como vocês combinaram de dividir?

**Comment by joaostein** [comment]
@fdaciuk tudo bem cara? estamos pensando em dar continuidade nesse capítulo.  você tem interesse em ajudar?

**Comment by gabrielfgularte** [comment]
@joaostein Vou pegar o cap6 e vou começar a traduzir ele. Depois quem entrar, se entrar mais alguém pra traduzir, pega outra metade da tradução.

**Comment by fdaciuk** [comment]
@joaostein vou ter que largar o osso, infelizmente não tá rolando pra eu continuar :(

Pode puxar a minha branch do link acima e continuar se quiser. Sorry :)

**Comment by joaostein** [comment]
Tranquilo @fdaciuk, sem stress.  se quiser fazer um PR para ficar registrado, fica a vontade :)

**Comment by fdaciuk** [comment]
Nem precisa @joaostein.. só adiciona minha branch no remote, faz um merge e continua xD

**Comment by SauloSilva** [comment]
@fdaciuk muito obrigado pela sua ajuda (=
@joaostein fiz um PR a partir da branch do @fdaciuk para darmos continuidade ao processo de tradução.

**Comment by joaostein** [comment]
Perfeito! valeu @SauloSilva e @fdaciuk!

**Comment by ericdouglas** [comment]
Vou colocar esse capítulo na gh-pages.

**Comment by randsonjs** [comment]
Fechado em favor da #266
