### ISSUE TITLE
Tempo para envio de PR

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#102]
Pessoal, acho que devemos adicionar no README um termo dizendo que após *X* dias que a pessoa se manifestou para realizar alguma tarefa, se ela não enviar nenhum PR, nós *adm's* temos a permissão para alterar a label do capítulo sem precisar confirmar com a pessoa.

Estamos com a situação de vários capítulos parados, e se alguém chegar e olhar rapidamente vai pensar que não tem mais nada disponível para traduzir.

Penso no período de 15 dias para cada interação.

**Ex**:

- Pessoa se manifestou dia 01 ~> tem até o dia 16 para enviar algo
- Enviou algo no dia 03 ~> tem até o dia 18 para enviar algo novamente

cc @joaostein @randsonjs @SauloSilva @gabrielfgularte

**Comment by ewertonorg** [comment]
Show de bola @ericdouglas

**Comment by SauloSilva** [comment]
@ericdouglas seria ótimo. 
Talvez ter um [contributing](https://github.com/blog/1184-contributing-guidelines) com estas especificações e outras mais seria muito importante.

**Comment by vitortalaia** [comment]
Boa ideia @ericdouglas. Eu mesmo gostaria de contribuir com as traduções, mas as labels indicavam que "quase tudo já estava sendo feito".

**Comment by ericdouglas** [comment]
@vitortalaia tem um capítulo disponível, e mais alguns parados...

O cap. livre é [esse](https://github.com/braziljs/eloquente-javascript/issues/19)

**Comment by gabrielfgularte** [comment]
Eu peguei o capítulo 20. Mas ainda não traduzi todo. Forkei e to commitando no meu repo o andamento da tradução. @ericdouglas, prefere que, a cada commit, eu vá fazendo PR?

**Comment by joaostein** [comment]
Concordo @ericdouglas.  acho que 1 PR a cada duas semanas é um tempo considerável.  Uma pergunta que me veio a cabeça é como vamos controlar isso para todos os capítulos? alguma ideia?

@SauloSilva -- Ter uma seção contributing com esses detalhes e outros que são relevantes para ajudar e orientar quem quer contribuir e participar, sou total a favor.  Se chegarmos nessa decisão, você poderia fazer um draft inicial para irmos iterando a medida que for necessário?  O que vocês acham:  um arquivo no repositório ou wiki page?

@gabrielfgularte -- sobre os commits, é interessante ir mandando pra podermos ter sempre a versão mais atual online.  quanto mais movimento melhor, motiva as outras pessoas.

**Comment by joaostein** [comment]
Uma ideia para controlar poderia ser esse flow:

1. Damos assign na issue p/ a pessoa que pediu
2. Colocamos uma milestone com 2 semanas de prazo
3. Quando tivermos milestones vencidas, nós verificamos a atividade da issue e incrementamos ou não o tempo da milestone p/ mais 2 semanas baseado na atividade da pessoa.
4. Dependendo de como for o caso (caso a pessoa não tenha atividades), podemos dar um ping para a pessoa e se ela não responder em alguns dias, nós abrimos a issue para outra pessoa.

**Comment by gabrielfgularte** [comment]
@joaostein Blz. Concordei com os outros pontos também.

**Comment by randsonjs** [comment]
Concordado com o @joaostein! :)

**Comment by ewertonorg** [comment]
:+1: @joaostein

**Comment by SauloSilva** [comment]
Super válido as questões que o @joaostein abordou, se todos estiverem de acordo faço o `draft `.
Acho que PR pequenos a cada tópico ou tópicos traduzidos pode alavancar o **andamento do projeto** e deixar as **reviews** um pouco mais fácil.

**Comment by ericdouglas** [comment]
Bom, como estamos todos de acordo, podemos resumir assim:

1. O colaborador tem prazo de 2 semanas para enviar um PR com alguma contribuição
1. O @SauloSilva fica responsável por criar o `CONTRIBUTING.md`
1. Quem fizer algum merge de PR, ou adição/modificação de uma label em alguma issue de tradução/revisão, fica responsável por criar/atualizar a milestone referente ao capítulo em questão, aumentando a *deadline* dessa milestone em **+14 dias** a partir de `new Date()` <strike>do dia da alteração</strike> (sempre caindo no mesmo dia da semana)

**Comment by joaostein** [comment]
Assim que tivermos um draft do `CONTRIBUTING.md`, o que acham de  iniciarmos um processo de verificação dos capítulos para liberar os que estão atrelados às pessoas que não podem contribuir por agora e abrir espaço para quem pode ajudar agora?

Além disso, podemos aproveitar essa movimentação para iniciar o processo de adicionar as milestones para cada capítulo e dar assign da issue para o responsável (o que hoje não estamos fazendo).

@SauloSilva — eu criei uma issue (#107) para o `CONTRIBUTING.md`, se precisar de qualquer ajuda, me dá um ping por lá!

**Comment by ericdouglas** [comment]
@joaostein perfeito assim!

@SauloSilva , se precisar de qualquer ajuda, me dá um ping por lá! [2]

**Comment by SauloSilva** [comment]
@joaostein e @ericdouglas belezera, irei precisar sim :D

**Comment by vitortalaia** [comment]
@ericdouglas Blz, eu posso continuar a tradução do cap. 12

**Comment by SauloSilva** [comment]
@joaostein aqui:

``
4 Dependendo de como for o caso (caso a pessoa não tenha atividades), podemos dar um ping para a pessoa e se ela não responder em alguns dias, nós abrimos a issue para outra pessoa.
``

esse **em alguns dias** poderia ter os dias específicados que tal? Ex: 7 dias(1 semana).

**Comment by ericdouglas** [comment]
@vitortalaia por favor, comente na issue do capítulo 12 que você vai traduzir, para ficar centralizado tudo lá naquela issue!

:smile:

**Comment by joaostein** [comment]
@SauloSilva perfeito! 7 dias é tempo suficiente para a pessoa responder, se ela demorar mais que isso podemos acreditar que a pessoa não está acompanhando e podemos abrir o capítulo para quem estiver interessado e puder contribuir com frequência.
