### ISSUE TITLE
Criar arquivo CONTRIBUTING.md

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#107]

**Comment by joaostein** [comment]
@SauloSilva @ericdouglas @randsonjs @gabrielfgularte @ewertonorg @vitortalaia  poderíamos fazer um brainstorm de ideias do que vamos colocar no contributing. daí organizamos logicamente as informações e criamos o primeiro draft e vamos iterando a medida que forem surgindo novas ideias, o que acham?

Alguns pontos interessantes:

* Explicar o que cada label significa (já está no readme)
* Explicar como é o fluxo de trabalho (já está no readme)
* Explicar o novo modelo de 2 semanas detalhado (#102)
* Explicar como contribuir de fato (já está no readme).  Aqui podemos colocar algumas informações mais detalhadas passo a passo para termos um workflow mais padrão e que fique mais fácil de controlarmos a atividade de cada issue (já pensando no modelo de 2 semanas).  Podemos pegar algumas ideias que foram comentadas no #57 e que tem um exemplo real em #9.
O controle ficaria mais o menos assim para cada PR que a pessoa fizer:

![](https://s3.amazonaws.com/f.cl.ly/items/1T1817441v1B443p3O1m/Screen%20Shot%202015-03-17%20at%203.38.34%20PM.png)

Se tiverem mais ideias vamos postando aqui e melhorando também as que já temos :)

**Comment by ericdouglas** [comment]
@joaostein as ideias que você mencionou são as que pensei inicialmente.

Vou pensar em mais coisas aqui...

**Comment by joaostein** [comment]
Beleza @ericdouglas!  essas já dão uma boa base para o @SauloSilva fazer um draft inicial.

Se você quiser, pode editar a descrição da issue e ir adicionando checkboxes com as ideias que forem aprovadas, e vamos marcando a medida que elas forem feitas.

Seguem algumas outras:
- Podemos colocar referência para pessoas que tenham pouco ou nenhum conhecimento em markdown (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet ou algum link semelhante).
- Podemos colocar uma seção com o workflow para abrir issues sobre dúvidas de como traduzir os termos (e olhar o glossário) e sempre adicionando a referência a issue original para podermos visualizar as atividades da issue

**Comment by ewertonorg** [comment]
O que vocês acham de detalhar também como usar o git?
[Exemplo] (https://github.com/luanfonceca/leitech/blob/master/docs/how_to_code.md)

**Comment by vitortalaia** [comment]
Eu gostei das ideias

**Comment by SauloSilva** [comment]
@joaostein e @ericdouglas acho que é isto mesmo, por hora ja conseguimos um draft inicial.

**Comment by ericdouglas** [comment]
Uma coisa que lembrei que faço e acho legal é adicionar todo o texto em inglês primeiro, fazer o commit e depois ir alterando traduzindo para pt-br, assim quem olhar os commits conseguirá ver em um local o texto original (mais fácil para revisar).

**Comment by joaostein** [comment]
@ericdouglas -- ótimo workflow! isso daí agiliza demais! vamos colocar um check-list na descrição dessa issue e marcando a medida que formos fazendo os PR's que finalizam eles, o que acha?

**Comment by ericdouglas** [comment]
Acho excelente @joaostein !

**Comment by gabrielfgularte** [comment]
:+1:

**Comment by SauloSilva** [comment]
@ericdouglas @joaostein @ewertonorg @vitortalaia @gabrielfgularte vocês tem algo a mais para acrescentar no arquivo?
Se não tiverem posso fechar esta _Issue_?

**Comment by ericdouglas** [comment]
@SauloSilva vou dar um PR ali, falta lembrar de colocar `#numero-da-issue` no commit para ficar registrado e facilitar para vermos as atividades na issue.

**Comment by SauloSilva** [comment]
@ericdouglas :+1:

**Comment by SauloSilva** [comment]
@ericdouglas e @joaostein não sei se vocês estão fazendo assim, mais pensei em colocarmos algumas restrições nas revisões tipo:

- Quem traduziu o capitulo não pode revisar nem supervisionar.
- Quem revisou o capitulo não pode supervisionar.

Assim teremos três pessoas diferente para finalização do processo. 
Acho que assim a chance de algo errado passar diminui muito.
O que acham? Se essa idéia fizer sentido para vocês adiciono isso no arquivo.

**Comment by joaostein** [comment]
Para mim faz bastante sentido.  Essa ideia de termos pessoas diferentes em processos diferentes ajuda a conseguirmos perspectivas diferentes e a diminuir a chance de erro.  Eu acredito que essa regra pode ser um pouco flexível em algumas situações.  Por exemplo, caso alguém que traduziu queira fazer uma supervisão em uma situação de label “aguardando” e ninguém para executá-lo — claro que nesse caso, uma terceira pessoa teria prioridade.  A ideia principal é eliminarmos qualquer burocracia que possa fazer que o projeto ande mais lentamente.

Eu gosto dessa ideia de orientarmos para que a execução passe por 3 pessoas diferentes, uma em cada etapa, tendo em mente que essa é uma regra que pode ser conversada e negociada em casos específicos :)

**Comment by joaostein** [comment]
Uma outra coisa que pode ser interessante colocar no arquivo é o workflow para tirar dúvidas quanto a tradução de certos termos.  Seguindo a linha da discussão que tivemos em #115 e em alguns outros exemplos.  Além disso, orientar a quem iniciou a thread a criar um PR no arquivo de glossário quando a issue tiver uma conclusão.

Eu estava lendo um post sobre manter documentação no wiki, dêem uma olhada [aqui](https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4).  como já temos um arquivo, podemos dar uma organizada e atualizada nele e mantermos tudo por ali, o que acham?

**Comment by SauloSilva** [comment]
@joaostein [bem lembrado](#issuecomment-84376580), acho que em casos específicos poderíamos usar a própria _Issue_ para darmos concessão a exceção. 
Concordo que isso deveria ser explicado no **CONTRIBUTING.md** se todos apoiarem esta idéia, ok?

A respeito [desta outra pergunta](#issuecomment-84379241) acho que o melhor é mater atualizado o que ja temos. Se todos concordarem, adiciono no **CONTRIBUTING.md**.

**Comment by ericdouglas** [comment]
@SauloSilva concordo cara, podemos deixar essa "regra", de que uma pessoa pode cuidar de apenas uma parte do processo, salvo situações onde ninguém mais esteja disponível para realizar a tarefa, como o @joaostein disse.

@joaostein bem lembrado! Após tirar a dúvida e definir como vai ser traduzida a palavra, a pessoa deve fazer um PR adicionando a palavra no [glossário](https://github.com/braziljs/eloquente-javascript/blob/master/glossario.md).

**Comment by joaostein** [comment]
Atualizei o arquivo com o passo a passo para dúvidas em tradução de termos, palavras, etc...

Se tiver algum passo que ficou confuso ou complexo, comenta [aqui](https://github.com/braziljs/eloquente-javascript/commit/7d8024c6f046e7f477717c0427efb83b0b9f2855) para melhorarmos.

**Comment by SauloSilva** [comment]
@joaostein :+1:

**Comment by joaostein** [comment]
o que precisamos para fechar essa issue?

**Comment by SauloSilva** [comment]
@joaostein da minha parte não vejo mais nada a acrescentar. 
@braziljs/eloquent-javascript alguém tem algo a mais para acrescentar aqui?

**Comment by ericdouglas** [comment]
Creio que podemos fechar!
