### ISSUE TITLE
Guia para o Website

### ISSUE THREAD

**Issue by randsonjs** [braziljs/eloquente-javascript#108]
Pessoas, esse é um guia vivo do que tem no website e na branch master onde está acontecendo as traduções/revisões. Se estiver faltando alguma coisa espero que deixem no comentário.

- [x] Introdução
- [x] Valores, Tipos e Operadores
- [x] Estrutura do Programa
- [x] Funções
- [x] Estrutura de Dados: Objeto e Array
- [x] Funções de Ordem Superior
- [x] A Vida Secreta dos Objetos
- [x] Prática: Vida Eletrônica
- [x] Erros e Manipulação de Erros
- [x] Expressões Regulares
- [ ] Módulos
- [x] Prática: A Linguagem de Programação
- [ ] JavaScript e o Navegador
- [x] O Document Object Model
- [x] Manipulando Eventos
- [x] Projeto: Plataforma de Jogo
- [x] Desenhando no Canvas
- [ ] HTTP
- [x] Formulários e Campos de Formulários
- [x] Projeto: Um Programa de Pintura
- [x] Node.js
- [x] Projeto: Website de Compartilhamento de Habilidades

Vou começar a atualizar o site assim que possivel e irei alterando aqui.

**Comment by gabrielfgularte** [comment]
Como está se dando a migração para o formato exigido pelo autor?

**Comment by randsonjs** [comment]
O site é feito em Jekyll @gabrielfgularte. E os arquivos são em markdown!

**Comment by gabrielfgularte** [comment]
@randsonjs Não tinha um lance que precisava ser no formato que ele usou lá? @ericdouglas e @joaostein lembram dessa discussão? Deixa catar a issue aqui...

**Comment by gabrielfgularte** [comment]
Aqui #66 . Mas já li tudo... acho que ficou bom do jeito que tá. ;)

**Comment by randsonjs** [comment]
E a outra migração existe @gabrielfgularte. Ela está na branch `official`. Mas eu fiquei responsável por passar os arquivos para o site. 

Os documentos no formato original traduzidos vão existir :)

Só estava esperando ter no minimo 5 capitulos traduzidos para começar a passar para lá. Mais tarde vou dar uma olhada e já começar a passar.

**Comment by gabrielfgularte** [comment]
Beleza pura, @randsonjs ! Qualquer coisa, pode falar que tento ajudar em algo. ^^

**Comment by joaostein** [comment]
@gabrielfgularte por enquanto não vamos nos preocupar com os outros arquivos.  vamos focar em organizar nosso workflow nesse repo e terminar a tradução.  acho que o mais valioso é termos o conteúdo disponível para a comunidade.  quando estiver pronto, aí pensamos em como será essa migração :)

**Comment by joaostein** [comment]
@randsonjs você poderia colocar os números nos capítulos? fica mais fácil a identificação

Outra coisa é que os arquivos ainda precisam ser revisados, e talvez seja interessante nós passarmos eles quando estiverem 100%, se não você vai ter que ficar atualizando toda vez que tiver um PR e mudar um pequeno detalhe... mas aí é com você, o que você achar melhor :smile:

**Comment by gabrielfgularte** [comment]
@joaostein perfeito! :)

**Comment by randsonjs** [comment]
Você está certissimo @joaostein. Por isso passarei apenas os capitulos que estarão já revisados.

Inclusive, é bom colocar um alerta no README dizendo que o website está na branch gh-pages. Caso precise modificar alguma coisa relacionada ao mesmo!

**Comment by ericdouglas** [comment]
@randsonjs vale lembrar que além da revisão, teremos a supervisão!

**Comment by joaostein** [comment]
@randsonjs -- precisa de alguma ajuda para atualizar o site com os capítulos que estão escritos?

**Comment by randsonjs** [comment]
Desculpa a demora galera, mas agora coloquei o capitulo 3 \o/. Os que vejo que já está com a issue fechada(completo) vou adicionando.

**Comment by SauloSilva** [comment]
Muito bom @randsonjs :clap: :clap:

**Comment by joaostein** [comment]
boooa!

**Comment by randsonjs** [comment]
Fechando em favor da #254. Não precisamos de dois status para o projeto do site ;)

**Comment by ericdouglas** [comment]
@randsonjs :+1:

**Comment by joaostein** [comment]
@randsonjs :+1:
