### ISSUE TITLE
Cap.05 - Funções de Ordem Superior

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#11]
Tradução do arquivo [05-funcoes-de-ordem-superior.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/05-funcoes-de-ordem-superior.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/05_higher_order.html)

**Comment by SauloSilva** [comment]
Revisando este.

**Comment by randsonjs** [comment]
Muito obrigado @SauloSilva. Estou mudando de casa e ficando sem internet :(

**Comment by ericdouglas** [comment]
@SauloSilva :+1:

**Comment by SauloSilva** [comment]
@braziljs/eloquent-javascript vou supervionar este ok?

**Comment by ericdouglas** [comment]
@SauloSilva como estávamos falando na outra issue, acho melhor focarmos em terminar os capítulos iniciais juntos.

Mas manda ver ai haha :satisfied:

**Comment by SauloSilva** [comment]
@ericdouglas este termino até Sábado (=

**Comment by joaostein** [comment]
@SauloSilva vai mandando os pedaços que eu vou ajudando você nos comentários :)

**Comment by ericdouglas** [comment]
@SauloSilva show então lol !!!

**Comment by SauloSilva** [comment]
@braziljs/eloquent-javascript este capítulo foi finalizado, por isso irei fechar esta issue.

@randsonjs tem como você inserir este capítulo no site, fazendo favor?

**Comment by randsonjs** [comment]
Vou inserir o mais rápido possivel @SauloSilva :)
