### ISSUE TITLE
acompanhar atualização no repositório do autor

### ISSUE THREAD

**Issue by ewertonorg** [braziljs/eloquente-javascript#112]
Como  iremos acompanhar as atualizações que estão sendo feitas no repo do autor do livro?

**Comment by joaostein** [comment]
@ewertonorg ótimo questionamento.  olhando o histórico do [repositório original](https://github.com/marijnh/Eloquent-JavaScript/commits/master), dá pra ver que as mudanças são constantes.

No momento que estamos, talvez seja interessante focar mais no trabalho de tradução e revisão para depois lidarmos com esse tipo de problema, visto que vamos ter revisões e supervisões de todos os capítulos antes de termos a versão final, garantindo uma versão mais atual. 

Respondendo a sua pergunta, a primeira ideia que me vem a cabeça seria com o apoio da comunidade através de PRs, o que acha?

Se tiverem outras ideias, podemos deixar registradas aqui para nos auxiliar lá na frente.

**Comment by ericdouglas** [comment]
No caso as alterações são o que? Correções de typo? O conteúdo, de forma geral, não irá ser alterado creio eu.

Correção de typo não interfere pra gente, só vai interferir se ele adicionar/retirar conteúdo, mas isso **acho** que não vai acontecer.

**Comment by SauloSilva** [comment]
@ewertonorg olhando para a [lista de commits](https://github.com/marijnh/Eloquent-JavaScript/commits/master) da pra notar que se tem correções ortográficas e visuais dos capítulos, mas adições de conteúdo so existe na [Errata](http://eloquentjavascript.net/errata.html).
A Errata é a única coisa que devemos nos atentar, pois erros ortográficos sera arrumado durante as reviews.
Caso algum erro ortográficos ou visual passe pelas duas revisões a comunidade ou leitor fica livre para contribuir com um PR de correção.

**Comment by ericdouglas** [comment]
@SauloSilva :+1:

**Comment by ewertonorg** [comment]
@SauloSilva , @ericdouglas , @joaostein  :+1:

**Comment by randsonjs** [comment]
Boa @ewertonorg. Qualquer dúvida você pode abrir uma issue para nós discutirmos ;)
