### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by SauloSilva** [braziljs/eloquente-javascript#114]
Atualmente estamos [linkando uma licença](http://creativecommons.org/licenses/by-nc/3.0/), não seria interessante termos uma dentro do repositório?
Talvez daria até pra usar alguma que o Github sugere, que tal?

**Comment by joaostein** [comment]
Sobre a licença, nós devemos manter a mesma usada pelo autor do livro para não termos nenhum tipo de problema legal.  Como fazemos referência a CC e a MIT no readme, não há necessidade de alteração nesse sentido. De qualquer forma, valeu pela ideia :smile:
