### ISSUE TITLE
Como traduzir a palavra "writable(s)"?

### ISSUE THREAD

**Issue by gabrielfgularte** [braziljs/eloquente-javascript#115]
A única sugestão que vem na minha cabeça é gravável / graváveis. Até pq, quando leio em inglês é assim que minha mente traduz, existindo essa palavra em português ou não. hahaha.

**Comment by gabrielfgularte** [comment]
Pensei em "de gravação" agora. O que acham? Por exemplo:

"Streams de gravação..."
"Métodos de gravação..."

**Comment by randsonjs** [comment]
Depende do contexto também. Onde se aplica?

**Comment by gabrielfgularte** [comment]
"_Strams_ [ de gravação | gravável | que pode ser sobescrito ] são um conceito amplamente usado..."

Acho que em todos os casos, pelo menos desse tópico do capítulo, cabe melhor o "de gravação" mesmo.

**Comment by ericdouglas** [comment]
Qual a frase, em inglês @gabrielfgularte ?

**Comment by gabrielfgularte** [comment]
Ahh sim, foi mal. rsrs.

"Writable streams are a widely used concept in Node interfaces."

**Comment by ericdouglas** [comment]
"Streams de escrita são um conceito largamente utilizado em interfaces do Node."

O que acham? =p

**Comment by gabrielfgularte** [comment]
Boa... Acho melhor que o "de gravação" mesmo, que tem a ver com read and write, ou seja, leitura e escrita. Não sei pq não pensei nisso antes... hahaha. O que acha @randsonjs ?

**Comment by joaostein** [comment]
"Streams de escrita" :+1:

**Comment by SauloSilva** [comment]
Stream de escrita. :+1:

**Comment by gabrielfgularte** [comment]
Fechado!
