### ISSUE TITLE
Cap.06 - A Vida Secreta dos Objetos

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#12]
Tradução do arquivo [06-a-vida-secreta-dos-objetos.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/06-a-vida-secreta-dos-objetos.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/06_object.html)

**Comment by mazulo** [comment]
Olá, caso o @joselitojunior não tenha mais a disponibilidade, eu me ofereço para ajudar. Esse capítulo é de um assunto que tenho estudado no livro que tenho lido (JS: The Good Parts). 

Sendo assim, eu gostaria só de saber se você @ericdouglas poderia me tirar uma dúvida.
Eu notei que os arquivos do livro que ainda não estão traduzidos estão vazios. Então como se daria a tradução? Eu tenho que pegar diretamente o livro original? 
Estou ajudando na tradução de outro projeto, mas lá tem o diretório dos arquivos originais, e o diretório onde ficará os arquivos traduzidos.

Desde já me desculpo se for uma pergunta muito besta, mas estou começando agora no mundo das contribuições :sweat_smile:

**Comment by ericdouglas** [comment]
@mazulo pode traduzir sim cara, não houve resposta do Joselito.

O arquivo está em branco pois o autor usa um sistema diferente do markdown, então como eu estou fazendo para traduzir?!

Vou no site do livro, copio o texto e vou passando para markdown. Após terminar essa formatação, inicio a tradução.

Se pensar em outra forma, sinta-se à vontade para nos dizer!

**Comment by mazulo** [comment]
Entendi. Bom, de primeira também vejo essa como a melhor maneira. 
Só pra reforçar: eu devo então transcrever o conteúdo do [capítulo](http://eloquentjavascript.net/06_object.html) em questão em inglês usando markdown, e então traduzir o conteúdo.

Sendo assim, eu me responsabilizo por começar a tradução dele. :smiley:

**Comment by ericdouglas** [comment]
Perfeito @mazulo , é isso mesmo!

Boa sorte! :smile:

**Comment by mazulo** [comment]
@ericdouglas estou começando agora a transcrição do capítulo. Desculpe a ausência. Estava acabando umas pendências de outro projeto :sweat_smile: mas agora vou botar pra gerar :smiley:

**Comment by ericdouglas** [comment]
Perfeito @mazulo ! Irei retomar as traduções em breve também!

:smile:

**Comment by mazulo** [comment]
@ericdouglas tive alguns contratempos com minha máquina, e acabei tendo que mandá-la para a garantia :disappointed: porém, consegui arrumar um reserva com um amigo que vai dar pro gasto hahaha retomando aqui as atividades \o

**Comment by ericdouglas** [comment]
hehe sem problemas @mazulo !

:smile: 

o/
