### ISSUE TITLE
Link para Download

### ISSUE THREAD

**Issue by movibe** [braziljs/eloquente-javascript#123]
Converti para ePub

1) Para Converter 
http://johnmacfarlane.net/pandoc/

2) Para Editar 
https://github.com/user-none/Sigil/releases

Link pra baixar
http://minhateca.com.br/movibe/eloquente-javascript,411419992.epub

**Comment by joaostein** [comment]
@movibe -- muito obrigado pelo interesse.  No estágio que estamos, não faz sentido termos um link para um build .epub já que os capítulos não estão finalizados e estão em constante mudança.  Além disso, esse processo será feito no final e usará a mesma build tool que o autor usou na versão original.  

Se você quiser e puder contribuir com as traduções e revisões, dá uma olhada no [arquivo de contribuição](https://github.com/braziljs/eloquente-javascript/blob/master/CONTRIBUTING.md) e se tiver qualquer dúvida pode abrir uma issue e perguntar que estamos aqui para ajudar :)

**Comment by movibe** [comment]
@joaostein Valeu João, é que na verdade eu preciso começar a ler ainda e pra mim ler melhor eu uso epub pra ler no celular, dai como achei o projeto muito interessante e estão de parabéns eu resolvi fazer essa versão pra mim e compartilhar com vocês, pois de repente, pode somar aos ideais do projeto.

Não posso garantir a contribuição, mas se eu puder com certeza irei contribuir e continuar acompanhando.

Um abraço e parabéns a todos que estão participando desse projeto!
