### ISSUE TITLE
Cap.07 - Prática: Vida Eletrônica

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#13]
Tradução do arquivo [07-pratica-vida-eletronica.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/07-pratica-vida-eletronica.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/07_elife.html)

**Comment by SauloSilva** [comment]
@ericdouglas e @endel este capítulo ainda esta em aberto? Se sim eu posso ajudar a dar continuidade a tradução.

**Comment by ericdouglas** [comment]
@SauloSilva , pode continuar pois não tivemos resposta.

**Comment by SauloSilva** [comment]
@ericdouglas vou começar a tradução então.

**Comment by ericdouglas** [comment]
Ótimo @SauloSilva ! :smile:

**Comment by endel** [comment]
Pode sim @SauloSilva! Valeu!

**Comment by SauloSilva** [comment]
@endel e @ericdouglas ok, obrigado :D

**Comment by ericdouglas** [comment]
Vou passar esse capítulo para a branch gh-pages :smile:
