### ISSUE TITLE
Canal de Comunicação

### ISSUE THREAD

**Issue by randsonjs** [braziljs/eloquente-javascript#132]
O @ewertonorg sugeriu usar uma ferramenta para comunicação. Tipo Gitter ou Slack. O que acham galera?

Seria interessante para colocar as ideias lá e interagimos melhor entre todos.

Por mim seria uma boa, e usaria Slack pela integração com o GitHub!

O que acham?

**Comment by ewertonorg** [comment]
O Slack é legal porque podemos ter mais de um sala pra nos comunicarmo
já o Gitter eu não sei se funciona da mesma forma.

**Comment by ericdouglas** [comment]
Interessante! Acho que o Gitter para um repositório faria mais sentido.

**Comment by gabrielfgularte** [comment]
Slack +1
Boa @ewertonorg!

**Comment by joaostein** [comment]
boa @ewertonorg!  esses serviços são free ou pagos?

**Comment by ericdouglas** [comment]
Na realidade, usar outros serviços para discutir coisas do projeto é algo ruim, pois fica muito mais difícil de rastrear depois, e de outras pessoas acompanharem.

Mas para ter algum tipo de interação mais informal entre os membros do projeto, acho super válido!

:smile:

**Comment by joaostein** [comment]
:+1: @ericdouglas

**Comment by randsonjs** [comment]
Acho bem interessante o Gitter. Por causa justamente da integração dele com o GitHub. 

Então cada issue ou pull-requeste novo ele mostra no chat. Sem contar que dá pra ver o perfil de quem fez a ação e tudo mais. Ele é simplesmente lindo kkk

**Comment by randsonjs** [comment]
Você tá certo @ericdouglas. Mas creio que existam mais coisas além que as issues não resolvem. Tipo algo em tempo real. Que nesse caso é bem melhor que as issues. 

E é mais para alguém falar como está indo ou avisar que acabou de enviar um pull-request. Coisa simples mesmo. 

Desculpa que eu estou no mobile e fechei e abri a issue sem querer :(

**Comment by SauloSilva** [comment]
Concordo plenamente com o @ericdouglas. Para fins open source é ruim.

**Pontos negativo**

- Cada um tem seu horário que se dedica ao open source. Algo real time é desnecessário.
- As conversas tende a sair da meada
- Logs de conversa é horrível de acompanhar
- Aumenta a complexibilidade de novos contribuidores entender o fluxo

Obs: Para fins de uma interação informal com a galera do projeto acho bem legal.

**Comment by ewertonorg** [comment]
@joaostein Sim são free!
@SauloSilva  e @ericdouglas   eu concordo com vocês, quando sugeri as ferramentas não pensei em substituir as issues. Mas sim para termos mais uma forma de interagir.

**Comment by randsonjs** [comment]
Entendo,

até pq quando quero comentar alguma coisa em relação ao projeto no privado eu falo com cada um. Pelo menos por enquanto está funfando tranquilo!

Vou fechar essa issue. Se gerar mais discussão em relação a isso eu reabro!
