### ISSUE TITLE
Cap.08 - Erros e Manipulação de Erros

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#14]
Tradução do arquivo [08-erros-e-manipulacao-de-erros.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/08-erros-e-manipulacao-de-erros.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/08_error.html)

**Comment by SauloSilva** [comment]
@braziljs/eloquent-javascript apesar de eu ter traduzido este; como não existe outra opção vou revisar este :smile: ok?

**Comment by joaostein** [comment]
boa @SauloSilva, manda ver :)

**Comment by joaostein** [comment]
Vou iniciar a supervisão desse capítulo, pode ser? :)

**Comment by ericdouglas** [comment]
@joaostein :+1:

**Comment by SauloSilva** [comment]
@joaostein perfeito.
