### ISSUE TITLE
Como vocês traduziriam o termo: "Debug"? 

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#155]
Me deparei com essa palavra na supervisão do capítulo 8 (#14 ).  Estamos usando hoje "depuração" para traduzir esse termo, o que é uma tradução válida.  Eu achei interessante levantar essa issue para discutir esse termo pois o verbo "Depurar" acaba se tornando muito formal, e muitas vezes acabamos falando algo na linha: "Debugar", "Debugando" etc...

O que vocês acham?  Mantemos essa linha formal (já que é uma tradução de texto), ou seguimos uma direção mais informal?

Seguem algumas referências:
* http://www.dicionarioinformal.com.br/depurar/
* http://michaelis.uol.com.br/moderno/portugues/index.php?lingua=portugues-portugues&palavra=depurar
* http://www.dicionarioinformal.com.br/debugar/
* http://michaelis.uol.com.br/moderno/portugues/index.php?lingua=portugues-portugues&palavra=debugar

@braziljs/eloquent-javascript

**Comment by ericdouglas** [comment]
@joaostein se colocarmos *debugar* indicamos de forma bem mais direta as tarefas para o leitor, remetendo-o já ao contexto do console.

Creio que seja melhor usar **debugar**.

**Comment by SauloSilva** [comment]
@joaostein eu prefiro a formal. Debugar acho que fica um termo meio inglês com português.

**Comment by joaostein** [comment]
Eu entendo e reconheço os dois lados.  Não penso que haja uma forma mais correta que a outra.  Um ponto interessante de fazermos um paralelo sera com a issue (#92), onde traduzimos de uma forma informal também, misturando inglês e português, o que pareceu fazer sentido nesse caso.

Acredito que o mais importante de tudo é mantermos uma consistência de modo que fique claro ao leitor o que estamos querendo dizer.

O que acham de esperar mais feedback do pessoal e tomamos uma decisão conjunta?

**Comment by randsonjs** [comment]
Não tem como @SauloSilva. A computação é com inglês e algumas palavas. Qualquer pessoa que for ler isso aqui vai saber o inglês técnico(no minimo).

Acho que o termo **debugar** faz mais sentido!

**Comment by vitortalaia** [comment]
Debugar :+1:

**Comment by SauloSilva** [comment]
@joaostein super válido a abertura desta _Issue_ para a discussão; a opinião de todos ajuda muito :smile:
Entendo @randsonjs mas não poderemos garantir de que todos leitores terão o conhecimento de termos técnicos, afinal este livro vem com o intuito de ajudar as pessoas que ainda não dominam a lingua inglesa; então quanto menos termos em inglês melhor será(lógico que existem palavras que não tem como traduzi-las). 
A palavra _debugar_ faz sentido neste contexto, mas por se tratar de um livro ainda prefiro introduzir as palavras na forma mais formal possível.

**Comment by joaostein** [comment]
Vejo aqui que a galera tem sentimentos divididos e tendem mais para a tradução com a versão “debugar”.

Para mim está claro que há mais uma divergência em relação ao leitor entender ou não o que está sendo comunicado baseado em duas premissas opostas.  Eu estou bastante inclinado em votar ao uso do termo mais informal “debugar” pelo fato de quando eu me coloco no lugar do leitor, acredito que gostaria de aprender os termos técnicos da forma como eles são usados na prática e que sejam um reflexo do que eu irei usar no dia-a-dia. Além disso, introduzir termos técnicos em inglês pode ser interessante para eu (como leitor) aumentar meu leque de entendimento desses termos.

Os pontos levantados para usar a tradução mais formal (depurar):
- Evitamos misturar Inglês com Português;
- Quanto menos termos em inglês melhor;
- Ajuda ao leitor compreender melhor, pois partimos da premissa que nosso leitor não sabe o inglês técnico básico;

Os pontos levantados para usar a tradução informal (debugar):
- Usamos uma linguagem mais direta e clara;
- O leitor irá entender, pois partimos da premissa que nosso leitor sabe o inglês técnico básico;
- Estimula o contato do leitor com termos técnicos que ele irá se deparar no dia-a-dia;
- Aumenta indiretamente o nível de conhecimento do inglês técnico do leitor;

---

Mensagem para a galera que está trabalhando nos capítulos (se esqueci de alguém sinta-se incluindo):

@gabrielfgularte @adrianotadao @leonascimento @fsbatista @WagnerMoreira @iagowp @vitornogueira @ewertonorg @mazulo @fdaciuk @leonardosouza 

Gostaria que chegássemos em uma conclusão lógica e plausível nessa issue nos próximos dias, então qualquer input aqui é super válido. Se não quiser adicionar argumentos, apenas um :+1: no termo que julgar ser o mais adequado já ajuda muito.  Muito obrigado :)

**Comment by vitornogueira** [comment]
Acho válidos todos os pontos levantados mas concordo com @SauloSilva em "... por se tratar de um livro ainda prefiro introduzir as palavras na forma mais formal possível..."
Depurar :+1:

**Comment by randsonjs** [comment]
:+1:

**Comment by ericdouglas** [comment]
@joaostein na realidade, traduzir o termo *debug* para **depurar** está semanticamente errado. É só analisarmos o significado de depurar nos links que você disponibilizou acima, algo totalmente distante e vago para o que queremos falar em nosso contexto.

Se a pessoa procurar por **debugar**, vai achar o significado exato da ação que deve ser feita, como [neste link](http://www.dicionarioinformal.com.br/debugar/):

> Muito usada por programadores, analistas de sistemas e demais profissionais de T.I. , a palavra **DEBUGAR** pode ser usada em uma situação em que precisamos analisar um determinado bloco de programação ou a execução de um programa para localizar possíveis erros ou "bugs" de sistema e também erros de programação.

Utilizar termos que não são os utilizados pelos profissionais e pela comunidade de forma geral para mim é um deserviço para o leitor.

**Debugar** :+1:

**Comment by joaostein** [comment]
@ericdouglas O termo "depurar" na realidade é válido para esse caso, dá uma olhadinha nesse [link](https://pt.wikipedia.org/wiki/Depura%C3%A7%C3%A3o) que tem uma explicação melhor

Só estou comentando para não influenciar a galera :smile:

Vamos esperar mais um pouco e ver se o resto do time (e pessoas que estejam só acompanhando e queiram ajudar de alguma forma) tem alguma contribuição, para em seguida fecharmos a issue baseado na divisão do sentimento da galera, de forma que fique claro e justo o motivo de escolhermos uma das duas opções.

**Comment by fdaciuk** [comment]
Pelas partes que traduzi do livro, deu pra ver que o escritor utiliza uma linguagem mais informal. No dia a dia é muito mais comum ouvir o termo **debugar** do que **depurar**. Olhando por esses pontos, concordo com o @ericdouglas: acho que de **debugar** faz mais sentido :)

**Comment by ericdouglas** [comment]
@joaostein por esse link sim hehe mas os outros de "dicionário", são bem diferentes, e são os que aparecem inicialmente na busca. :smile:

**Comment by iagowp** [comment]
Eu prefiro o **debugar**. Assumindo que uma pessoa está tendo seu primeiro contato com programação por este livro, é provável que ele não tenha ouvido nenhuma das duas palavras. Por outro lado, ele muito provavelmente já ouviu falar do bug de algum jogo, e contextualmente, me parece mais compreensível o debugar.

Além disso, eu acho que é de mais valia ao leitor se habituar aos termos técnicos mais frequentemente encontrados num ambiente de trabalho, e eu pessoalmente acho que nunca ouvi alguém falar depurar fora da universidade.

**Comment by fsbatista** [comment]
Entendo a preocupação com o formalismo, mas creio que neste caso o ganho de objetividade do termo 'debugar' prevaleceria sobre perda do formalismo obtido por depurar.

**Comment by WagnerMoreira** [comment]
@joaostein Por ser uma tradução deveria ser mais formal, porém subentende-se que quando a pessoa se deparar com **debugar**  e não entender bem o seu significado ela vai pro google, concordo com o ganho de objetivo ela vai estar habituada com essa palavra daqui em diante se ela não conhecer
Só vi depurar em windows, e isso traz más lembranças acredito que as pessoas podem se negativar com **depurar** :sweat_smile:

**Comment by joaostein** [comment]
Valeu a todo mundo que contribuiu.  Atualizei o Glossário para referência futura! (95fba38b1051a8fd10e1674d840e4d2aa46fbc3c)

**Comment by SauloSilva** [comment]
@joaostein  acho que minha idéia foi a única que convergiu do restante mas todos comentários foram convincentes e me fez pensar de uma outra forma, agora não vejo problemas na troca de depurar para debugar. Obrigado galera :)
