### ISSUE TITLE
Tradução do Capítulo 20

### ISSUE THREAD

**Issue by gabrielfgularte** [braziljs/eloquente-javascript#159]
Pessoal, pintou um projeto grande aqui na empresa e ta tomando o tempo que eu havia reservado para a tradução. Deve acabar ainda essa semana, espero que até quarta. Sei que já devo estar a mais de 15 dias sem fazer um PR da tradução, e isso pode estar atrasando o andamento do projeto.

Peço desculpas, e, espero na quinta retomar a tradução. Caso vocês queiram passar a tradução para alguém, tudo bem. Mas se puderem aguardar até quinta (7/5), eu pretendo voltar a traduzir.

Obrigado e grande abraço!

**Comment by ericdouglas** [comment]
@gabrielfgularte sem problemas cara! Pode iniciar dia 7 :smile:

**Comment by gabrielfgularte** [comment]
Opa! Valeu @ericdouglas ! =D

**Comment by joaostein** [comment]
massa @gabrielfgularte, não se preocupa, a ideia é ser um side project que todos fiquem felizes e que não atrapalhe a agenda de ninguém :smile:
