### ISSUE TITLE
Cap.10 - Módulos

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#16]
Tradução do arquivo [10-modulos.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/10-modulos.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/10_modules.html)

- [x] Texto Original & estrutura, @letanure,  #28 
- [x] Modules #43 
- [x] Organization #44
- [x] Namespaces
- [x] Reuse
- [x] Decoupling
- [x] Functions as namespaces
- [x] Objects as namespaces
- [x] Detaching from the global scope
- [x] Evaluating data as code
- [x] Require
- [x] Slow-loading modules
- [x] Interface design
- [x] Predictability
- [x] Composability
- [x] Layered interfaces
- [x] Summary
- [x] Exercises
- [x] Month names
- [x] Circular dependencies
- [x] A return to electronic life

**Comment by ericdouglas** [comment]
Removendo label para outra pessoa poder continuar a tradução.

**Comment by ewertonorg** [comment]
Se não tiver ninguém com este capitulo eu posso continuar a tradução. @ericdouglas

**Comment by ericdouglas** [comment]
Beleza @ewertonorg ! Pode continuar!

**Comment by ewertonorg** [comment]
:v::smiley:

**Comment by ericdouglas** [comment]
Vou continuar a tradução deste capítulo :smile:
