### ISSUE TITLE
Definições para termos em gerais

### ISSUE THREAD

**Issue by SauloSilva** [braziljs/eloquente-javascript#163]
A minha idéia é construir um padrão a ser seguido durante todos os processos. 

#### Termos a definir:

- [x] delimitação para títulos de obras
- [x] citações
- [x] sentido figurado
- [x] estrangeirismo
- [x] marcação para código

Iniciamos uma discussão neste [PR](https://github.com/braziljs/eloquente-javascript/pull/161#discussion_r29989969) sobre os termos de sentido figurado, gostaria de dar continuidade para saber a opinião de todos. 
Caso alguém tenha algum outro termo para adicionar fique a vontade.

Aqui está minhas considerações sobre cada item.

- **delimitação para títulos de obras:** aspas duplas no nomes da obra e o nome do autor entre parênteses. Ex: "The Book of Programming"(Master Yuan-Ma)
- **citações:** utilizar aspas duplas.
- **sentido figurado:** utilizar _itálico_ em todas ocorrências.
- **estrangeirismo:** utilizar _itálico_ em todas ocorrências.
- **marcação para código:** inserir o pedaço de código entre apostrofe. Ex: `console.log`

Depois da definição de todos seria bem válido registrarmos essas decisões em algum lugar, pensei em coloca-las no CONTRIBUTING, o que acham?

**Comment by joaostein** [comment]
Boa @SauloSilva!

Só para ficar mais organizado as ideias que foram levantadas e outras:

1. **Estrangeirismo** - Convencionar que **todos** os termos em inglês sejam em *itálico* (ex: *bug*)
2. **Sentido Figurado** - Evitar ao máximo usar as aspas.  Usar somente nos casos em que queremos dar destaque/ênfase mesmo em algum termo bem específico que seja usado de forma figurada, lembrando que comparações não entram (ex: é um pensamento "cristalizado")
3. **Citações** - acredito que usar aspas duplas seja o mais válido

Eu não entendi muito bem o que você quis dizer com os itens "delimitação para títulos de obras" e "marcação de code", poderia explicar?

Sobre adicionar no CONTRIBUTING eu acho super válido.  Após termos uma direção, poderíamos criar uma seção no arquivo que contém essas regras para fácil consulta.

**Comment by SauloSilva** [comment]
Boa @joaostein, irei detalhar os dois itens:
- marcação de código é definir como destacaremos um pedaço de código no meio de um texto. A minha opinião é usar apóstrofe para ficar tipo assim: `code`
- delimitação para títulos de obras são as referências de livros que o autor faz no inicio de cada capitulo depois de uma citação, vou mostrar um exemplo: Master Yuan-Ma, The Book of Programming. Qual seria o melhor jeito de demarcar isto? Pensei em algo do tipo: "The Book of Programming"(Master Yuan-Ma) mas não estou tão certo que isto seria correto.

**Comment by joaostein** [comment]
Valeu @SauloSilva! Atualizei acima com meu ponto de vista sobre esses itens.  Para ficar mais rico, você poderia colocar seu ponto de vista em cada um dos outros itens? Dessa forma, ao final da issue podemos fechar com a ideia de todos que quiseram participar e contribuir, pode ser? :)

**Comment by SauloSilva** [comment]
@joaostein fiz as minhas considerações.

**Comment by joaostein** [comment]
Show! vamos esperar o feedback do pessoal.  Um pergunta rápida:  Qual a vantagem de alterar a forma como os títulos das obras são apresentados (em relação ao original)?

**Comment by ericdouglas** [comment]
Vamos lá pessoal! Minhas considerações sobre os tópicos levantados:

* **Delimitação para títulos de obras** - Podemos deixar da forma que está no original. Quanto menos alterarmos, mais fácil é de manter tudo padronizado na nossa tradução, sem contar que `menos regras === menos burocracia` :smile:  
* **Estrangeirismo** - Convencionar que todos os termos em inglês sejam em *itálico* (ex: *bug*)
* **Sentido Figurado** - Usar quando também houver alguma sinalização no texto, mas sempre utilizar aspas.  
* **Citações** - usar aspas duplas e o sinal `>` para representar citação no markdown.
* **Marcação para código** - Manter o uso que está sendo feito hoje. Blocos de código para os exemplos e códigos inline quando fazemos referências a qualquer coisa relacionada a código no meio do texto (nomes de funções, variáveis, valores primitivos, etc...) e não traduzir código (comentários, nome de variáveis etc)

**Comment by SauloSilva** [comment]
@joaostein e @ericdouglas acho que é isto mesmo, adicionei estas questões que definimos no **contributing** ok?

**Comment by ericdouglas** [comment]
Perfeito @SauloSilva ! Obrigado cara :smile:

**Comment by joaostein** [comment]
Show @SauloSilva! já dei o merge :smile:

**Comment by SauloSilva** [comment]
valeu @joaostein
