### ISSUE TITLE
Presente de Natal

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#176]
Galera, estou querendo finalizar este projeto antes do Natal para ficar de presente para a comunidade.

Para ajudar nisso, pensei em algumas coisas:

1. Tentarmos dedicar 10min ~ 15min todo dia ao projeto e
2. Trabalharmos todos no mesmo capítulo

Creio que se formos finalizando todas as etapas de um capítulo antes de ir para o próximo, vamos ter mais sucesso. Dessa forma, uma pessoa incentiva a outra.

O que acham? Quem topa participar?

Se entrarmos nessa forma de trabalho, não existirão mais "donos" dos capítulos, assim que terminarmos um, já começaremos outro, e caso tenham mais pessoas querendo ajudar, repartimos as tarefas novamente e vamos prosseguindo. :smile: 

Aguardo a opinião/voto de vocês. 

@braziljs/eloquent-javascript

**Comment by SauloSilva** [comment]
:+1: eu topo 

:gift: :santa: para comunidade JS.

**Comment by joaostein** [comment]
eu também! vamos nessa!

**Comment by ericdouglas** [comment]
Boa @SauloSilva e @joaostein ! o/

Vamos ver quem mais anima, e iniciamos no sábado (01/08). O que acham?

**Comment by randsonjs** [comment]
Muito boa a ideia @ericdouglas!

**Comment by SauloSilva** [comment]
@ericdouglas por mim combinado.

**Comment by ericdouglas** [comment]
@SauloSilva :+1:

**Comment by joaostein** [comment]
@ericdouglas @braziljs/eloquent-javascript o que vocês acham de darmos uma geral naquelas milestones e colocarmos algumas datas realistas para conseguirmos terminar no natal?

**Comment by ericdouglas** [comment]
Verdade @joaostein , ótima sugestão. Como você sugere que façamos as projeções?

**Comment by joaostein** [comment]
@ericdouglas, eu não sei ainda como podemos projetar isso, porque não sabemos a velocidade/quantidade de pessoas que vão nos ajudar nos outros capítulos (por enquanto: você, @SauloSilva e eu).  Talvez uma saída boa seja iniciarmos o capítulo 02, e ver em quanto tempo conseguimos fechar, assim conseguimos ter uma noção da velocidade e fazer uma projeção baseada nela.  Se percebermos que não vai dar tempo até o Natal, teríamos duas opções (que não excluem um da outra):

- Aumentar a quantidade de tempo investido por semana
- Sensibilizar mais pessoas que queiram ajudar e aumentar a velocidade

Seria muito legal ouvir as ideias de cada um para chegar em uma conclusão que faça sentido para todo mundo :)

**Comment by ericdouglas** [comment]
@joaostein pensei basicamente nisso mesmo.

Não divulguei no fcbk novamente pois gostaria de ver o quanto conseguiríamos entregar dessa forma, e ver se vai funcionar legal.

Após esse capítulo podemos divulgar e ver se conseguimos mais adeptos a causa.

:smile:
