### ISSUE TITLE
Cap.12 - JavaScript e o Navegador

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#19]
Tradução do arquivo [12-javascript-e-o-navegador.md](https://github.com/cerebrobr/eloquente-javascript/blob/master/chapters/12-javascript-e-o-navegador.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/12_browser.html)

**Comment by ericdouglas** [comment]
Removendo label para outra pessoa poder continuar a tradução.

**Comment by vitortalaia** [comment]
Vou continuar a tradução a partir do tópico HTML

**Comment by ericdouglas** [comment]
Show @vitortalaia !

**Comment by SauloSilva** [comment]
vou dar continuidade na tradução deste aqui!

**Comment by ericdouglas** [comment]
@SauloSilva :+1:

**Comment by ericdouglas** [comment]
@SauloSilva este é o **último capítulo** (:tada:)  que falta para finalizarmos a tradução do livro, os outros já estão traduzidos e publicados no site.

Como anda a tradução ai?

Se não estiver podendo finalizar esse trabalho, só nos avisar para que outra pessoa finalize :smile:

**Comment by ericdouglas** [comment]
Pelo que pude ver no [original](http://eloquentjavascript.net/12_browser.html), este capítulo já está traduzido, falta apenas remover a parte inglês.

Como não tivemos retorno, vou assumir esse capítulo, removendo o conteúdo em inglês e passando a tradução para o branch `gh-pages` :)
