### ISSUE TITLE
Cap.13 - O Document Object Model

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#20]
Tradução do arquivo [13-document-object-model.md](https://github.com/cerebrobr/eloquente-javascript/blob/master/chapters/13-document-object-model.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/13_dom.html)

**Comment by iagowp** [comment]
Eu gostaria de revisar este capitulo

**Comment by randsonjs** [comment]
É seu @iagowp ;)

**Comment by ericdouglas** [comment]
@iagowp :+1:

**Comment by SauloSilva** [comment]
@iagowp como estamos na revisão deste?

**Comment by iagowp** [comment]
Opa, foi mal. Eu devo terminar essa semana.

**Comment by SauloSilva** [comment]
@iagowp :+1:

**Comment by ericdouglas** [comment]
Vou colocar esse capítulo na branch gh-pages.
