### ISSUE TITLE
Atualizar conteúdo do site

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#206]
@randsonjs, você consegue atualizar o site com o conteúdo que nós temos até agora e deixar em sincronia a medida que novas alterações forem ocorrendo?

**Comment by SauloSilva** [comment]
@joaostein :+1:

**Comment by randsonjs** [comment]
Consigo sim mano! Estarei atualizando o mais rápido possivel ;)

**Comment by randsonjs** [comment]
Só me da um toque, quaís capitulos já posso separar para atualizar no site?

**Comment by ericdouglas** [comment]
@randsonjs acho que tem duas opções que fazem sentido:

1. colocar no site assim que for traduzido, para depois atualizar com a versão final, revisada e supervisionada. Ou
2. colocar no site depois todas as etapas concluídas.

O que vocês acham melhor @randsonjs , @joaostein @SauloSilva @gabrielfgularte ?

ps: A opinião do @randsonjs tem um grande peso pois ele está tomando conta dessa parte hehe :smile: 

Minha opinião é que podemos colocar após a tradução e talvez adicionar o link do .md referente ao capítulo, para quando a pessoa achar algo errado enviar um PR.

**Comment by SauloSilva** [comment]
@ericdouglas sou a favor da **opção 1**. E deixar claro que não é a versão final.
Isso é motivador para nós contribuidores de ter sempre um conteúdo em produção (mesmo não estando 100%) e assim já disponibilizaremos muito material para possíveis leitores.

**Comment by ericdouglas** [comment]
@SauloSilva exato, penso dessa forma também!

**Comment by joaostein** [comment]
estou com vocês, gosto da ideia de colocar assim que for sendo feito.  @randsonjs nesse caso, há alguma coisa que não estamos vendo que possa bloquear ou que possa fazer sua vida mais difícil?

**Comment by SauloSilva** [comment]
@joaostein, @randsonjs e @ericdouglas verifiquei aqui e tem bastante capítulos para colocar em produção, isso é muito bom (=

Acho que vai sobrecarregar para o @randsonjs será que não poderíamos compartilhar esta tarefa, igual estamos fazendo nos capítulos para revisão?

Se todos estiverem de acordo, conseguimos ter todos no ar até sexta (=

**Comment by randsonjs** [comment]
HAHAHAHAHA, não precisa @SauloSilva. Vou tirar um dia pra poder mexer neles! ;)

Farei o mais rápido que puder, está na lista de a fazeres!

**Comment by SauloSilva** [comment]
Tranquilo @randsonjs  (=
Mas se precisar de ajuda pode contar comigo.

**Comment by joaostein** [comment]
+1

**Comment by joaostein** [comment]
ref #108
