### ISSUE TITLE
Display Hints

### ISSUE THREAD

**Issue by gabrielfgularte** [braziljs/eloquente-javascript#207]
Galera, como a gente vai fazer (ou vem fazendo) pra traduzir essas partes dos exercícios? Eu vi pelo menos umas quatro formas diferentes. Exemplos:

- https://github.com/braziljs/eloquente-javascript/blob/master/chapters/19-projeto-um-programa-de-pintura.md
- https://github.com/braziljs/eloquente-javascript/blob/b94c2ec478ffcf47f6f3dfb7f7e4f864e1331103/chapters/16-desenhando-no-canvas.md#L682
- https://github.com/braziljs/eloquente-javascript/blob/b94c2ec478ffcf47f6f3dfb7f7e4f864e1331103/chapters/13-document-object-model.md#L559
- https://github.com/braziljs/eloquente-javascript/blob/a016975f2bfa24a621767b249f97613b3c662ac9/chapters/09-expressoes-regulares.md#L698

Quando eu traduzi, eu olhei um desses e segui, achando que havia um padrão. Mas aparentemente não. No site ele só mostra a dica quando o usuário clica em mostrar. Vamos repetir esse padrão?

**Comment by ericdouglas** [comment]
lol 4 formas diferentes mesmo auhhauahuha

Por mim pode ser **Dica** ou **Dicas**, dependendo da quantidade.

**Comment by gabrielfgularte** [comment]
@joaostein @SauloSilva O que acham?

**Comment by SauloSilva** [comment]
@gabrielfgularte estou com o @ericdouglas, **Dicas**

**Comment by gabrielfgularte** [comment]
Beleza então. Amanhã padronizo esses blocos antes de seguir pra tradução.

E quanto a apresentação disso no site? Vamos seguir o modelo do site original?

**Comment by joaostein** [comment]
+1 dicas

sobre o site, não sei se precisamos gastar muita energia com esse nível de detalhe por agora. tenho a impressão de que focar em melhorar o conteúdo possa ter mais valor imediato ao leitor.

**Comment by gabrielfgularte** [comment]
Concordo. Mas queria saber como fariam isso... :)

**Comment by joaostein** [comment]
a princípio acredito que espelhar tudo do original

**Comment by randsonjs** [comment]
Hoje no site temos um bloco de código com um compilador de js igual ao original. Na verdade copiado de lá :smile: 

Então fazer igual não seria dificultoso. Visto q já está implementado muita coisa!

**Comment by gabrielfgularte** [comment]
Acho a boa também, só não sabia se tínhamos infra pra isso. Como tem, acho muito válido. Mas não deveríamos ter uma marcação específica pra essa área? Como o site vai entender que precisa fazer a "mágica" nessa linha?

**Comment by joaostein** [comment]
@gabrielfgularte -- vou fechar essa issue pois a discussão divergiu para um assunto diferente do tópico inicial da issue.  se quiser continuar essa conversa, pode abrir um issue individual, beleza?
