### ISSUE TITLE
Atualizar CONTRIBUTING.md

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#217]
Galera, precisamos atualizar o arquivo de contribuições para refletir o novo workflow.

Como definimos:
- Não haverá mais “donos” de capítulos
- Acredito que muitas labels que temos não irão mais fazer sentido, visto que os PRs podem vir de qualquer pessoa a qualquer momento e para qualquer parte do livro (senda elas grandes ou pequenas), descaracterizando esse fluxo que temos: tradução > revisão > supervisão. Toda melhoria é melhoria independente do estágio que o capítulo está.
- O fluxo que temos hoje também foi alterado baseado nesse novo modelo.

Esqueci de algum outro ponto importante? Alguém tem mais algum feedback em relação a isso antes de iniciarmos o processo de atualização do doc?

**Comment by joaostein** [comment]
// cc @braziljs/eloquent-javascript

**Comment by ericdouglas** [comment]
Acho que é isso mesmo @joaostein . Iremos agora dividir a tarefa em partes iguais de acordo com o número de interessados no momento em realizar tal tarefa.

**Comment by gabrielfgularte** [comment]
Boa!
