### ISSUE TITLE
Ajuda com trecho

### ISSUE THREAD

**Issue by gabrielfgularte** [braziljs/eloquente-javascript#222]
Fala galera, tudo bem? No contexto abaixo, como vocês traduziriam a parte grifada?
> **It also calls the function it is a method of** but takes its arguments normally, rather than as an array.

Obrigado!
@ericdouglas @SauloSilva @joaostein

**Comment by joaostein** [comment]
**Original:**
> There is a method similar to `apply`, called `call`. It also calls the function it is a method of but takes its arguments normally, rather than as an array. [...]

**Sugestões:**
> Existe um método similar ao `apply` chamado `call`. **Ele também chama a função que o possui como método** e aceita argumentos normalmente, ao invés de um array. […]

ou

> Existe um método similar ao `apply` chamado `call`. **Ele também chama a função na qual ele é um método** e aceita argumentos normalmente, ao invés de um array. […]

Mais ideias?

**Comment by gabrielfgularte** [comment]
Boa, pra não atrasar a tradução, eu optei por:
> Ele também chama a função da qual é um método por si própria

Mas acho que não ficou legal... De qualquer forma prefiro a sua segunda sugestão, @joaostein. Me parece fazer mais sentido.

PS.: Vou cancelar o PR atual, corrigir e então faço um novo. Ok?

**Comment by joaostein** [comment]
@gabrielfgularte -- não precisa fechar, basta fazer um novo commit no mesmo branch que ele atualiza automaticamente. se quiser fazer perfeito, é uma boa prática dar um [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) nos commits em um único commit com a descrição final (evitando ficar dois ou mais commits para cada correção que você fizer, poluindo o log dos commit).

após fazer o squash, você pode dar um `git push origin <branchName> -f` que ele sobrescreve o branch com o único commit.  Depois disso nós damos merge :)

Valeu demais, Gabriel!

PS. Se precisar de ajuda só dar um ping

**Comment by gabrielfgularte** [comment]
Beleza, vou utilizar sua primeira opção, já que ninguém mais se manifestou, ok? Aí você me ajuda com o squash depois?

**Comment by ericdouglas** [comment]
@gabrielfgularte desculpa o atraso em responder!

Achei a primeira opção do @joaostein melhor. Qual você vai usar?

[Nesse comentário](https://github.com/braziljs/eloquente-javascript/issues/222#issuecomment-133547611) você falou que gostou da segunda opção, e [nesse comentário](https://github.com/braziljs/eloquente-javascript/issues/222#issuecomment-134321315) falou que vai usar a primeira :stuck_out_tongue_winking_eye:

**Comment by gabrielfgularte** [comment]
Segunda, @ericdouglas ! Desculpas! HAHAHAH. Escrevi primeira querendo dizer segunda. xD

**Comment by ericdouglas** [comment]
@gabrielfgularte ahuuhahau xD
