### ISSUE TITLE
[LOG] Capítulo 05 - Funções de Ordem Superior

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#243]
Essa issue tem o propósito de manter um log de todas as alterações referentes ao capítulo, não sendo um espaço para discussões, dúvidas e sugestões. Caso queira contribuir, abra uma issue/pull-request individual com sua contribuição.

**Atenção**: Quando abrir uma issue ou pull request referente a esse capítulo, faça referência usando:
`ref "#243"`.

**Arquivo**: [05-estrutura-do-programa.md](https://github.com/braziljs/eloquente-javascript/blob/master/chapters/05-funcoes-de-ordem-superior.md)

**Original**: [link](http://eloquentjavascript.net/05_higher_order.html)

**Comment by randsonjs** [comment]
Esse capitulo encerrou? Ou ainda está em tradução? To perguntando pq o @SauloSilva falou para [colocar no website](https://github.com/braziljs/eloquente-javascript/issues/11#issuecomment-138178231).

**Comment by SauloSilva** [comment]
@randsonjs terminou sim. O que eu fiz fui a supervisão o último processo que faltava nele.

**Comment by randsonjs** [comment]
[Adicionado](http://eloquentjavascript.com.br/chapters/funcoes-de-ordem-superior/) :tada:
