### ISSUE TITLE
Viagem

### ISSUE THREAD

**Issue by gabrielfgularte** [braziljs/eloquente-javascript#251]
Pessoal, me desculpem. Eu entrei de férias e estou viajando, só volto dia 17. Deveria ter avisado antes, mas todas as vezes que lembrava ou esquecia em seguida, ou não tinha internet/dispositivo para enviar uma mensagem ou criar a issue.

Assim que voltar dou um gás! Desculpas novamente e abraço!

@joaostein @ericdouglas @randsonjs

**Comment by ericdouglas** [comment]
@gabrielfgularte show, aproveita ai brother! :sunglasses:

**Comment by randsonjs** [comment]
Tranquilo mano, aproveita as férias :sunglasses:

**Comment by joaostein** [comment]
Relaxa gabriel, aproveita bastante :)
