### ISSUE TITLE
[#220] CAP2 - Switch

### ISSUE THREAD

**Issue by evansantos** [braziljs/eloquente-javascript#253]
Boa tarde senhores,
Eu vi que na parte do switch no site do eloquent está só como rainy ao invés de chuvoso e quando fui forkar pra arrumar isto, vi que no .md do arquivo está tudo escrito em inglês...

O que devo fazer para ajudar?

**Comment by ericdouglas** [comment]
@evansantos muito obrigado por ver essa diferença!

O correto é o código estar **100% em inglês**!

Para correções no site você deve atualizar os arquivos da branch [gh-pages](https://github.com/braziljs/eloquente-javascript/tree/gh-pages).

Esse arquivo que você citou está [aqui](https://github.com/braziljs/eloquente-javascript/blob/gh-pages/chapters/estrutura-do-programa/index.md). :smile: 

Obrigado mais uma vez! Vendo mais erros fique à vontade para reportar/consertar! :smiley: 

cc/ @randsonjs

**Comment by randsonjs** [comment]
Qualquer alteração no site, pode ser feito pela branch `gh-pages`.

Muito obrigado por querer ajudar @evansantos, agradecemos a colaboração ;)
