### ISSUE TITLE
Status Geral do Projeto

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#254]
Nessa issue vamos listar todos os capítulos do projeto e listar seus respectivos status, que são:

- `não traduzido`
- `parcialmente traduzido`
- `traduzido`
-  `online` (capítulo no site)

## Capítulos

Capítulo | Status | Log
:--|:--|:--:
Introdução | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/279)
1. Valores, Tipos e Operadores | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/287)
2. Estrutura do Programa | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/220)
3. Funções | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/288)
4. Estrutura de Dados: Objeto e Array | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/215)
5. Funções de Ordem Superior | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/243)
6. A Vida Secreta dos Objetos | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/219)
7. Prática: Vida Eletrônica | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/336)
8. Erros e Manipulação de Erros | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/337)
9. Expressões Regulares | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/338)
10. Módulos | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/284)
11. Prática: A Linguagem de Programação | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/339)
12. JavaScript e o Navegador | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/285)
13. O Document Object Model | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/340)
14. Manipulando Eventos | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/341)
15. Projeto: Plataforma de Jogo | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/342)
16. Desenhando no Canvas | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/343)
17. HTTP | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/286)
18. Formulários e Campos de Formulários | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/344)
19. Projeto: Um Programa de Pintura | `traduzido` `online` |  [⎙]()
20. Node.js - (Parte 3: Node.js) | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/218)
21. Projeto: Website de Compartilhamento de Habilidades | `traduzido` `online` | [⎙](https://github.com/braziljs/eloquente-javascript/issues/345)

**Comment by ericdouglas** [comment]
Pessoal, estou com dificuldade em ver qual o status de cada capítulo. 

Alguns estão com a issue fechada, mas acho que não passaram pela revisão/supervisão completa.

Como sugerem fazer essa verificação?

cc/ @joaostein @SauloSilva @gabrielfgularte @randsonjs

**Comment by joaostein** [comment]
acredito em melhoria contínua.  acredito que esse status deveria representar `traduzido` ou `não traduzido/incompleto`.  penso que a revisão é algo contínuo que será feito através de PRs dos próprios leitores (e pessoas que, por vontade própria, se candidatam a ajudar com as melhorias), principalmente porque sempre vamos ter como melhorar (seja gramática, imprecisão de tradução, consistência, etc…).

Essa issue pode ser o _ponto de referência_ com essa tabela que contém todas as informações necessárias de cada capítulo, sendo elas: **status**, **log**, **link p/ site**. (mais ideias aqui são bem-vindas :smile:)

Depois, podemos limpar (fechar) todas as issues abertas (exceto essa) para fácil acesso/visualização das informações relevantes que estarão contidas aqui.

A medida que novos PRs de melhoria forem sendo feitos, vamos adicionando `ref #issue-de-log-do-capitulo` sempre que dermos merge (caso não tenha sido feito pelo próprio autor do PR) para termos tudo referenciado.

Dessa forma eliminamos essa noção de “etapas” e passamos a pensar em um processo contínuo de melhoria, eliminando qualquer tipo de burocracia para novas pessoas participarem do projeto e, além disso, ser bem flexível quando fizermos novas contribuições.

O que acham? algum feedback, ideias e argumentações? o mais importante é que todos fiquem felizes e satisfeitos com o direcionamento :)

**Comment by ericdouglas** [comment]
@joaostein dessa forma fica excelente, pois agora precisamos apenas fechar a tradução e passar para o site e pronto, finalizamos!

Se todos tiverem de acordo, só precisamos atualizar a tabela com as labels:

- `não traduzido`
- `tradução incompleta`
- `traduzido`
- `online`

**Comment by ericdouglas** [comment]
Listei o status de todos os capítulos!

Vou ir terminando as tarefas do início para o final, então os capítulos não traduzidos irei traduzir e depois deixar online.

Minha próxima tarefa vai ser deixar o cap. 6 online.

:smile:

**Comment by gabrielfgularte** [comment]
Boooa! Ótima iniciativa!

A propósito... voltei de viagem, mas to enrolado com uns projetos zumbi aqui... hahahaha. Em breve retomo as contribuições. (em breve espero que seja amanhã ou depois, no máximo.)

**Comment by ericdouglas** [comment]
Show @gabrielfgularte ! :+1:

**Comment by SauloSilva** [comment]
Pessoal acho que deveríamos manter as labels, eu não entendi o motivo da remoção. Sem elas ficou tudo muito confuso e nosso `CONTRIBUTING.md` ficou inconsistente.
E após o capítulo ser supervisionado e inserido no site (capítulo finalizado), acho que a issue deveria ser fechada.

cc/ @ericdouglas @joaostein @gabrielfgularte @randsonjs

**Comment by ericdouglas** [comment]
@SauloSilva achei que a sugestão do @joaostein válida pois dessa forma a responsabilidade de consertar os "bugs" será de todos, principalmente de quem estiver lendo.

Mas nada impede <strike>só a falta de tempo</strike> de revisarmos os capítulos da mesma forma feita anteriormente.

**Comment by SauloSilva** [comment]
@ericdouglas a idéia do @joaostein não impede de termos label nas issues que ainda falta (tradução, revisão, supervisão), acho que as labels nos da a noção do que falta no capítulo. O fechamento das issues depois do término do ciclo também é válido, por exemplo existem alguns capítulos que já foram supervisionados e que poderia ter suas issues fechadas.

Acho também que todos os capítulos traduzidos sem revisão ou supervisão deveriam estar publicados no site, mas suas issues deveriam ser mantidas abertas e com o estado atual (labels), assim o leitor que achar algo errado no site poderá entrar no repositório e ver que o capítulo ainda não esta finalizado, sendo assim haverá a possibilidade de contribuição para o processo.

Acho que a gente tinha um sistema legal nas issues antes, só estava faltando o conteúdo ser publicado.

E para ajudar o processo contínuo acho que um **CI** resolveria o problema, pois atualmente temos dois trabalho, do merge e da publicação no site que ainda é manual.

Resumindo, sou a favor de voltarmos com as labels, fechar as issues finalizadas (supervisionadas), publicar tudo que temos traduzido que esta na master e pensarmos em uma estrutura para o site suportar integrações/deploys automáticos quando houver atualizações de conteúdo.

**Comment by ericdouglas** [comment]
@SauloSilva fazendo estes passos que você citou (e que estávamos fazendo) é a forma mais profissional de se fazer.

Hoje, o que estou focado é entregar o nosso MVP, que consiste na tradução de todos os capítulos e na publicação dos mesmos.

Creio que podemos focar no MVP agora e depois decidimos os próximos passos.

**Comment by randsonjs** [comment]
Boa @ericdouglas, também gostei da ideia do mvp.

**Comment by joaostein** [comment]
Respondendo @SauloSilva :

> Pessoal acho que deveríamos manter as labels, eu não entendi o motivo da remoção. Sem elas ficou tudo muito confuso e nosso CONTRIBUTING.md ficou inconsistente

A primeira coisa que precisamos entender é se após fizermos as etapas de “revisão” e “supervisão” ainda teremos espaços para melhorias (seja ela gramática, tradução, typos, atualização de conteúdo, etc…)? Se isso for um fato verdadeiro, as labels de “revisão” e “supervisão” acabam perdendo o sentido, pois elas não são _finitas_. Elas não são uma etapa que tem um início e fim, sendo um processo contínuo que conta com a colaboração de todos (nós e os próprios leitores).

Sobre o `CONTRIBUTING.md`, assim que chegarmos em um consenso, podemos atualizá-lo para que fique consistente.

> E após o capítulo ser supervisionado e inserido no site (capítulo finalizado), acho que a issue deveria ser fechada.

Com certeza. Concordo no fechamento das issues para facilitar a manutenção do projeto. Quanto menos issues abertas melhor, pois fica mais fácil para novas pessoas contribuírem sem ficarem “perdidas” com a quantidade de informação. Por isso, a ideia de manter apenas uma issue central com todos os dados do capítulo (link p/ log, status e link p/ site) pode ser uma saída interessante para resolver esse problema.

> acho que as labels nos da a noção do que falta no capítulo (como tu disse ali em cima “estou com dificuldade em ver qual o status de cada capítulo)

Assumindo o fato de que sempre haverá condições para melhorias nos capítulos, nunca vamos saber de fato quando um capítulo está finalizado, pois ele estará em constante evolução. Acredito que a ideia principal é que lancemos a tradução inicial (podemos usar labels nesse caso, pois a tradução inicial é finita) de cada capítulo, e em seguida, mantemos a manutenção contínua que envolve melhorias.

> Acho também que todos os capítulos traduzidos sem revisão ou supervisão deveriam estar publicados no site […]

Absolutamente.

> […] mas suas issues deveriam ser mantidas abertas e com o estado atual (labels), assim o leitor que achar algo errado no site poderá entrar no repositório e ver que o capítulo ainda não esta finalizado, sendo assim haverá a possibilidade de contribuição para o processo

A contribuição de melhoria pode ser feita tanto antes quanto após o capítulo estar “finalizado” (leia traduzido), por isso, não faz muita diferença manter labels e issues específicas abertas após a tradução inicial estar completa.

***

Respondendo @ericdouglas:

> Hoje, o que estou focado é entregar o nosso MVP, que consiste na tradução de todos os capítulos e na publicação dos mesmos.

Com certeza. Além disso, organizar as issues e deixar tudo preparado para aceitarmos PRs de melhorias. Esses PRs podem vir de nós mesmos ou outras pessoas que estejam lendo ou queiram ajudar. Eliminamos a ideia de “donos” de capítulos/etapas de revisão+supervisão e deixamos o processo bem suave de melhoria contínua.

**Comment by ericdouglas** [comment]
> "Eliminamos a ideia de “donos” de capítulos/etapas de revisão+supervisão e deixamos o processo bem suave de melhoria contínua."

Estou mais inclinado para essa abordagem, pois assim nos libera para trabalharmos em outros projetos, e eventualmente ajudar em melhorias neste.

**Comment by randsonjs** [comment]
> Hoje, o que estou focado é entregar o nosso MVP, que consiste na tradução de todos os capítulos e na publicação dos mesmos.

O @ericdouglas está fazendo PR de uma série de capitulos para adicionar no site. Eu estava pensando em apenas adicionar os que já estiverem ok. Mas essa abordagem do `MVP` está sendo ótima.

Assim que puder ajudar para adiciona-los ao site farei :smile:

**Comment by SauloSilva** [comment]
@ericdouglas e @joaostein hoje nosso cenário esta meio bagunçado, eu mesmo olhei para as Issues e não consegui ver o que está traduzido, revisado e o que esta faltando.

Estou tentando levantar o ponto que devemos organizar nossas Issues (acho que foi o ponto principal desta Issue **Status Geral do Projeto**).

Obs: Concordo em eliminarmos os processos de revisão e supervisão para deixarmos mais tranquilo :+1:

**Comment by ericdouglas** [comment]
@SauloSilva essa issue nasceu para isso, já fiz este trabalho e está na tabela lá em cima. Olhe a tabela e você vai saber o status de cada capítulo, **a tabela está atualizada/correta**!

Tinha levantado o status de cada capítulo também, mas como estamos seguindo esse modelo de tradução/site, estava desnecessário ter os outros status listados.

Acho que não tem o que ser feito mais em relação a organização etc...  Agora é finalizar o que está pendente. Será mais útil se você investir seu tempo nisso :smile:

**Comment by SauloSilva** [comment]
¬¬

**Comment by ericdouglas** [comment]
@SauloSilva 

**Esclarecendo**: O que eu li/entendi era que você **estava fazendo** o levantamento dos capítulos para saber seus respectivos status, e no caso estaria fazendo algo que já estava feito e sendo assim perdendo tempo. 

Porém o que você disse é que quer propor uma forma para organizarmos melhor nossas issues. *Bem diferente do que eu entendi!*

**Perdão** por ter respondido algo diferente do que você falou, **MAS** você nos ajudaria **MUITO** se abrisse uma nova issue então para tratar desse assunto, pois essa issue é para tratar do **status do projeto**.

> informação pessoal: Eu separo + ou - 30 minutos do dia para dedicar nesse projeto, e o que eu menos quero é gastar tempo em issue, pois ainda tem bastante coisa a ser feita. Por isso eu leio bem rápido as issues para focar nas tarefas.

Acho melhor focarmos o tempo que tivermos finalizando o *MVP*, e depois discutir sobre as demais coisas.

A tabela dessa issue já nos dá o controle suficiente para fechar o projeto, não precisamos de mais burocracia agora, **IMHO**.

Não vai me ajudar em nada o controle de issues **agora**, as issues estarem corretas é algo **muito importante** quando finalizarmos as traduções e divulgarmos o projeto como finalizado.

Ai sim, nessa hora, onde pessoas irão vir ajudar aleatoriamente, devemos estar com todas as issues super bem organizadas.

Bom, acho que esclareci as informações que não ficaram claras e/ou erradas, e o que estou pensando ser o melhor para o projeto neste momento.

Acho que o clima do projeto está de cooperação e de amizade, não vamos deixar perder esse sentimento, pois para mim é o mais importante em qualquer projeto open source.

**Comment by SauloSilva** [comment]
@ericdouglas :+1:

**Comment by randsonjs** [comment]
É isso ai @ericdouglas, falou e disse ;)

**Comment by SauloSilva** [comment]
@braziljs/eloquent-javascript inseri o projeto no site da [brasiljs](http://braziljs.org/projetos/).

![ylydrs_uvzyf8pxsxhlhaevyyznx6rj6vfv3s2t11r4](https://cloud.githubusercontent.com/assets/1027336/10252591/cfa6486a-690e-11e5-9579-307fff684945.png)

**Comment by ericdouglas** [comment]
@SauloSilva :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by randsonjs** [comment]
:clap: :clap: :clap: :clap:

**Comment by joaostein** [comment]
Boa, @SauloSilva!

Sobre as issues, é isso que o @ericdouglas falou.  essa issue irá conter todos os dados necessários.  durante essa semana, vamos atualizando todo dia um pouco as issues de LOG que faltam, p/ quando formos fazer as referências já está tudo esquematizado.

Quando terminarmos todas, podemos fechá-las para deixar a lista de issues apenas com essa issue “Status Geral” aberta, facilitando a navegação no projeto p/ todos e deixando apenas o # das issues de log disponíveis para usarmos em cada novo PR que vier.

Saulo -- o que você acha dessa estratégia p/ deixar as issues mais organizadas e menos confusas? tem alguma sugestão de melhoria ou algo que talvez estaríamos deixando passar despercebido?

**Comment by SauloSilva** [comment]
@joaostein acho que esta ok. Nada a acrescentar :+1:

**Comment by ericdouglas** [comment]
Agora temos todos os capítulos traduzidos no site!!! :tada:

**Comment by randsonjs** [comment]
:tada: :tada: :tada: :tada:

**Comment by joaostein** [comment]
:tada: booa!

**Comment by SauloSilva** [comment]
sucesso galera :smile:  :tada:

**Comment by rands0n** [comment]
Ainda faz sentido ter isso aberto?
