### ISSUE TITLE
Como traduzir o termo Wrapper

### ISSUE THREAD

**Issue by rafaelcfreire** [braziljs/eloquente-javascript#273]
Boa tarde prezados,

Estou trabalhando na tradução do Cap.:17 onde o termo Wrapper é amplamente usado. Procurei em outros capítulos pelo termo e no 11 é utilizado o termo invólucro, eu preferiria encapsulador ou até mesmo manter o termo em inglês Wrapper uma vez que ele é normalmente usado em outras fontes em português.

**Comment by ericdouglas** [comment]
Boa tarde @rafaelcfreire !

Cara, eu concordo com você que *wrapper* é a melhor forma. Meu voto seria para não traduzir essa palavra.

**Comment by randsonjs** [comment]
+1 @ericdouglas

**Comment by SauloSilva** [comment]
sem tradução :+1:

**Comment by ericdouglas** [comment]
@rafaelcfreire como a maioria dos votos é para deixar sem traduzir, vamos fechar essa issue e deixar decidido que a palavra *wrapper* não precisa ser traduzida.

Caso depois alguém se manifeste contra, voltamos a discutir sobre. :smile:

**Comment by rafaelcfreire** [comment]
Excelente, darei continuidade usando <i>wrapper</i>, devo abrir uma issue para que o termo seja tratado de maneira uniforme nos outros capítulos, uma vez que existem ocorrências de traduções variadas para o termo?

**Comment by ericdouglas** [comment]
Pode abrir a issue sim @rafaelcfreire .

Vou atualizar o [glossário](https://github.com/braziljs/eloquente-javascript/blob/master/glossario.md) com este termo.

**Comment by joaostein** [comment]
+1 wrapper.  sorry pelo delay :)
