### ISSUE TITLE
[LOG] Capítulo 12 — JavaScript e o Navegador

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#285]
Essa issue tem o propósito de manter um log de todas as alterações referentes ao capítulo, não sendo um espaço para discussões, dúvidas e sugestões. Caso queira contribuir, abra uma issue/pull-request individual com sua contribuição.

**Atenção**: Quando abrir uma issue ou pull request referente a esse capítulo, faça referência usando:
`ref "#285"`.

**Arquivo**: [12-javascript-e-o-navegador.md](https://raw.githubusercontent.com/braziljs/eloquente-javascript/master/chapters/12-javascript-e-o-navegador.md)

**Original**: [link](http://eloquentjavascript.net/12_browser.html)

**Comment by SauloSilva** [comment]
@braziljs/eloquent-javascript vou continuar a tradução deste aqui.
