### ISSUE TITLE
Arrumar o prettyprint

### ISSUE THREAD

**Issue by SauloSilva** [braziljs/eloquente-javascript#293]
Estou abrindo esta Issue só para esclarecer a alteração feita no site.

**Situação:** Estava chamando `prettyPrint()` e não tinha nenhum js do pretty print inserido na página.
**Solução:** Inserir o prettyprint.js
**Resultado:** Todos os blocos de código apareceram com um syntax color.

**Comment by ericdouglas** [comment]
@SauloSilva show, cara! :clap: :clap: :clap: :clap: :clap:

**Comment by joaostein** [comment]
bom demais @SauloSilva!!
