### ISSUE TITLE
CAP2 - Retornando valores

### ISSUE THREAD

**Issue by rodolphoasb** [braziljs/eloquente-javascript#313]
Não sei se estou postando isso da forma correta, porém a tradução do projeto está assim:

"Por exemplo, a função Math.max recebe qualquer quantidade de valores numéricos e retorna o maior deles."

No livro em inglês está:

"Here a call to Math.min, which is the opposite of Math.max, is used as an input to the plus operator:"

Acredito que a tradução correta deve ser algo como:

"Aqui uma chamada para a função Math.min, que é o oposto da função Math.max, é usada como uma entrada para o operador +".

**Comment by joaostein** [comment]
Valeu, querido. Abri um PR resolvendo esse problema. O livro está em constante evolução e, por isso, é muito fácil achar espaços para melhorias, correções e ajustes.  Quando encontrar qualquer possibilidade dessas, pode mandar um PR (dá uma olhada no nosso [contributing](https://github.com/braziljs/eloquente-javascript/blob/master/CONTRIBUTING.md)) ou, se preferir, pode abrir a issue que alguém ficará de olho :+1: 

Valeu demais pela contribuição!
