### ISSUE TITLE
Capítulo 2 - #220

### ISSUE THREAD

**Issue by rodolphoasb** [braziljs/eloquente-javascript#315]
Retirar a parte:

"[TODO:] Adicionar link correto com âncora para a sessão mencionada no texto original: http://eloquentjavascript.net/04_data.html#array_indexing [/TODO]"

Valeu galera! Abraço!

**Comment by joaostein** [comment]
valeu querido. se quiser fazer um PR, fica a vontade :)

qualquer dúvida, dá uma olhadinha no [guia](https://github.com/braziljs/eloquente-javascript/blob/master/CONTRIBUTING.md) :+1:

**Comment by evansantos** [comment]
@joaostein já foi feito essa?

**Comment by italo-batista** [comment]
Encontrei essa issue aberta, mas pelo que entendi o equívoco já foi corrigido. Estou certo?

**Comment by ericdouglas** [comment]
Já foi corrigido sim. Obrigado pessoal! :smile:
