### ISSUE TITLE
Dominio está fora

### ISSUE THREAD

**Issue by ghost** [braziljs/eloquente-javascript#328]
O Dominio http://eloquentjavascript.com.br/ está inacessivel.

**Comment by ericdouglas** [comment]
ping @rands0n

**Comment by ericdouglas** [comment]
@rands0n @joaostein tem ideia porque está fora do ar?

O projeto está completo agora, todos capítulos traduzidos e na branch `gh-pages`.

Após o site voltar ao ar, podemos divulgar o trabalho na [weekly](https://github.com/braziljs/weekly).

**Comment by rands0n** [comment]
Putz, esqueci de fazer o pagamento. Farei o mais rápido possivel!

**Comment by leonardosoares** [comment]
Vlw! LGTM @rands0n

**Comment by joaostein** [comment]
valeu pelo report, leonardo!

@rands0n assim que estiver ok só dar um close nessa issue :+1:

**Comment by SauloSilva** [comment]
@rands0n se tu não pagou ainda acho melhor deixa em aberto ainda pois tenho um ponto de vista que gostaria de compartilhar aqui.

Seguinte: acho meio injusto o valor do domínio sair do bolso do @rands0n e como isto é um projeto open source (não envolve fins lucrativos) o ideal seria optarmos por algo `free`.

Sendo assim trago 2 opções para discutirmos:

1-  Utilizar o https://js.org/
2- Fazer uma arrecadação para reembolsarmos o @rands0n 

Eu voto pela 1 opção.
O que vocês acham @ericdouglas @rands0n e @joaostein?

**Comment by joaostein** [comment]
Fala galera, beleza?

Primeiramente, espero que tenham tido um ótimo natal e ano novo!

Sobre os pontos do @SauloSilva, eu penso o seguinte:

> o @rands0n fica injustiçado com esta despesa. 

Isso só o @rands0n para dizer. Seria uma boa deixar um feedback para entendermos melhor a situação.

> Sendo um projeto open source (não envolve fins lucrativos) o ideal seria optarmos por algo free, para ninguém ter despesas com nada.

Se houver alguém que queira bancar o domínio, não vejo problemas em ser algo pago. Caso não tenhamos ninguém disposto a pagar (ou dividir as despesas), nesse caso, podemos optar por uma solução free — o próprio autor ofereceu para hospedarmos a versão em português no domínio oficial e acredito que seja um passo interessante para a maturidade desse projeto (mesmo tendo a possibilidade de usar o domínio _eloquentjavascript.com.br_). Isso provavelmente irá envolver a migração do estado atual do livro para a versão _forkada_ no formato original (como conversamos no início do projeto a respeito de converter markdown para asciidoc).

> Utilizar o https://js.org/ - http://eloquentjavascript.js.org ainda esta liberado

:-1: Acredito que se formos na linha em busca de algo “free”, o ideal seria iniciar o processo de conversão para compatibilidade com o domínio oficial do livro — _eloquentjavascript.net_

cc @braziljs/eloquent-javascript

**Comment by rands0n** [comment]
Tudo bem pessoal ;)

O problema não é pagar. É que não utilizo cartão de crédito, e toda vez que ter que fazer o pagamento tenho que imprimir o boleto e fazer o pagamento em alguma agência. Nada contra pagar, pago com gosto. Mas acontece que toda vez esqueco :(

Em relação a buscar algo free, acho bacana.

Se alguém utiliza cartão de crédito e gostaria de pegar pra não cair novamente [fala comigo direto pelo email](mailto:orandson@gmail.com) que passo o dominio :D

Eu provavelmente vou esquecer mais vezes :(

Desculpa pessoal...

**Comment by rands0n** [comment]
Coloquei no dominio do GitHub Pages por enquanto. Assim que estiver disponivel faço a atualização.
