### ISSUE TITLE
Cade o Eric?

### ISSUE THREAD

**Issue by leonascimento** [braziljs/eloquente-javascript#346]
@joaostein  ou @SauloSilva  alguém tem notícia de @ericdouglas ? tô preocupado pq faz muito tempo que não vejo, posts, contribuições dele; Será que ele está bem?

**Comment by rands0n** [comment]
Então, ele não tem atividade no GitHub(que estava sendo diariamente) desde Novembro de 2015. Estou achando que aconteceu alguma coisa. Estamos tentando conversar com ele pelo email também desde o ano passado.

Infelizmente sem sucesso! :(

Se tiver acontecido alguma coisa nós não teremos como saber agora.

**Comment by leonascimento** [comment]
@rands0n  eu tinha contato direto com ele mano! fiquei preocupado mesmo! Sei lá se pode ter acontecido algo e ninguém tá sabendo. Ou penso que ele desligou-se das redes pra focar nos estudos e voltar com muita surpresa. Eu espero que seja isso mesmo,  torço pra que ele esteja bem.
ninguém tem cel dele ou outra forma de contato além do email?  :hushed:

**Comment by joaostein** [comment]
fala leo! Estamos tentando nos comunicar com ele sem sucesso. se alguém que estiver lendo e souber de algo (ou tiver como entrar em contato com ele direto), por favor, nos dê uma luz.

por enquanto, temos que aguardar :worried:

**Comment by leonascimento** [comment]
vlw @joaostein vamos ficar no aguardo então! Eu queria que ele tivesse sendo um front fora do Brasil cara merece por gente boa e o principal ser importante pra comunidade!

**Comment by ericdouglas** [comment]
Está tudo bem galera, voltei :+1:
