### ISSUE TITLE
Preparar para leitura e download no gitbook

### ISSUE THREAD

**Issue by gilsondev** [braziljs/eloquente-javascript#347]
Pessoal,

Não seria interessante também adaptar para que possa ser lido como também baixar nos formatos PDF, Epub e Mobi (para e-readers) no gitbook?

Porque ai teria mais opções de leitura.

**Comment by rands0n** [comment]
Infelizmente não, tivemos um problema com o autor do livro nesse sentido. Para evitar problemas nós apenas disponibilizamos em formato `.md` e no site.

Você pode fazer uma conversão sua. Mas espero que não seja publicado e também não leve o nosso nome e da organização justamente por esse fato :(

Isso foi a primeira coisa que queríamos fazer :D. Mas `¯\_(ツ)_/¯`

**Comment by gilsondev** [comment]
Ou seja, o código está sobre creative commons e o código sobre a licença MIT. Controverso ao extremo né? rs

Uma pena.

**Comment by gilsondev** [comment]
Vou fazer offline mesmo então. Valeu pela informação :)

**Comment by rands0n** [comment]
HAHAHAHA eu te entendo.

Também pensamos a mesma coisa. Vou fechar essa issue então. Abraços.
