### ISSUE TITLE
Erro no site

### ISSUE THREAD

**Issue by andersonweb** [braziljs/eloquente-javascript#348]
Caminho dos links está redirecionando errado. Com isso, a página exposta é de erro (404 Page not found).

**Comment by rands0n** [comment]
Bah, reparei agora isso! Assim que tiver um tempinho arrumo! :D

**Comment by andersonweb** [comment]
xD

**Comment by rands0n** [comment]
Fechado pela #349

**Comment by SauloSilva** [comment]
valeu @rands0n e @andersonweb (=

**Comment by adamsalves** [comment]
Olá pessoal.
Ainda temos um link fora. O `path` que leva ao início está redirecionando para http://braziljs.github.io/ e não a página inicial do projeto. Podemos reabrir essa issue? @rands0n @SauloSilva @andersonweb 
Valeu
![captura de tela de 2016-02-15 10 51 12](https://cloud.githubusercontent.com/assets/2552756/13049189/5be12a38-d3d2-11e5-93db-dad18913e77e.png)

**Comment by rands0n** [comment]
Olá Adams,

você pode enviar um PR fazendo isso também!? :D

Realmente ví esse problema agora. Acredito que seja coisa simples :)
—
Randson Oliveira

**Comment by adamsalves** [comment]
Posso mandar sim @rands0n :D
