### ISSUE TITLE
Status do projeto

### ISSUE THREAD

**Issue by candidodmv** [braziljs/eloquente-javascript#358]
Fala galera, 
Primeiramente, gostaria de parabenizar à todos que participaram desta iniciativa. Com certeza esse conteúdo irá ajudar muitas pessoas.

Agora gostaria de fazer uma sugestão. Não consegui encontrar informações sobre o status atual do projeto, se a tradução está concluída, se não o que falta?

Um grande abraço.

**Comment by joaostein** [comment]
Fala @candidodmv, tudo bem?

As informações de cada capítulo estão organizadas [nessa issue](https://github.com/braziljs/eloquente-javascript/issues/254).

Sobre o estado atual, basicamente [várias pessoas](https://github.com/braziljs/eloquente-javascript/graphs/contributors) traduziram diferentes partes do livro e, por isso, existem diversas oportunidades de melhoria na tradução e na própria gramática dos capítulos.

Hoje em dia, estamos revisando o que já está traduzido, focando na qualidade e precisão da tradução e entendimento do texto como um todo, além de tentar aplicar a gramática mais correta possível.

Se você tiver interesse em ajudar, dá uma olhadinha no [guia](https://github.com/braziljs/eloquente-javascript/blob/master/CONTRIBUTING.md) e, se tiver qualquer dúvida, só perguntar ;)

**Comment by joaostein** [comment]
só para dar um update: atualizamos o README para deixar essas informações mais acessíveis: e9fa03aec4219fe347d5c95411340476bac22b7b

**Comment by candidodmv** [comment]
Valeu João!
