### ISSUE TITLE
Publicar versão em PDF

### ISSUE THREAD

**Issue by timarcosdias** [braziljs/eloquente-javascript#369]
Estive pensando em publicarmos uma versão do livro traduzido em PDF para aqueles que nem sempre têm acesso à internet.

Encontrei um módulo que pode ajudar: https://github.com/alanshaw/markdown-pdf

Só nos restaria o problema de manter essa versão sincronizada com as modificações que forem feitas aqui no repositório. Eu mesmo poderia gerar uma nova versão periodicamente.

O que acham? Alguma sugestão?

**Comment by ericdouglas** [comment]
@timarcosdias legal cara! Podemos testar sim :)

Depois que conseguir gerar o pdf, mande um PR com o arquivo para este repositório dentro da pasta `pdf`.

Ai depois linkamos o arquivo no site :smile: 

Sobre a atualização, a gente vai gerando outras versões de acordo com a necessidade.

**Comment by timarcosdias** [comment]
Estou tendo dificuldades com a estilização no `markdown-pdf`. Assim que tiver um tempinho, vou arriscar o `github-markup`. Dizem que ele apresenta melhores resultados.

**Comment by timarcosdias** [comment]
Acabo de fazer o PR da primeira versão em PDF. Utilizei GitBook e Calibre. Fico aguardando o parecer do pessoal pra vermos o que dá pra melhorar.

**Comment by ericdouglas** [comment]
Creio que podemos fechar essa issue, algum problema que for encontrado depois a gente abre outra issue pontual.

Muito obrigado pela contribuição @timarcosdias ! :pray:
