### ISSUE TITLE
CAP4 - Data Structures

### ISSUE THREAD

**Issue by victorsilent** [braziljs/eloquente-javascript#379]
Original: "The binary in operator, when applied to a string and an object..."  
Tradução: "O binário no operador, quando aplicado à uma string e um objeto..."  

Possível correção: "O operador binário _in_, quando aplicado à uma string e um objeto..."

---

Original: "When we have two numbers, 120 and 120, we can consider them precisely the same number, whether or not they refer to the same physical bits."  
Tradução: "Quando temos dois números, 120 e 120, que podem, se eles se referem aos mesmos bits físicos ou não, serem considerados os mesmos números precisos..."  

Possível correção: "Quando nós temos dois numeros, 120 e 120, nós prodemos considerar que são o mesmo número, eles se referenciando aos mesmos bits físicos ou não."

**Comment by ericdouglas** [comment]
Obrigado pelas correções @victorsilent ! :smile:
