### ISSUE TITLE
Versão Epub

### ISSUE THREAD

**Issue by rafaelbezerra195** [braziljs/eloquente-javascript#382]
Bom dia pessoal, 

No repositório original temos um link para a versão Epub do livro( eloquentjavascript.net/Eloquent_JavaScript.epub ), vcs acham que seria uma boa opção dessa tradução também ter uma versão epub? 

Por um lado desencoraja a venda pelo menos digital do livro original, mas facilita a leitura mesmo não estando de frente ao computador. 

Só abri essa issue, pois o original tem a versão epub. 

Desde já, parabéns pelo trabalho.

**Comment by ericdouglas** [comment]
Acho válido sim, só precisamos encontrar uma ferramenta para fazer a conversão 
`.md -> .{pdf,mobi,epub}`

**Comment by rafaelbezerra195** [comment]
Vi algumas coisas por cima, mais de converter html -> xhtml, algo do tipo. Se eu encontrar algo publico aqui. 

Obrigado pela resposta.

**Comment by marcio-ti** [comment]
eu faço a criação do epub

**Comment by joaostein** [comment]
dêem uma olhada nesta issue: #347 

caso precisem de alguma ferramenta, dá uma olhada no [Pandoc](http://pandoc.org/).
