### ISSUE TITLE
Erro na função X explicação

### ISSUE THREAD

**Issue by leresche** [braziljs/eloquente-javascript#384]
http://braziljs.github.io/eloquente-javascript/chapters/estrutura-do-programa/

var num = Number(prompt("Digite um número", "0"));

**if (num < 0)**
    alert("Pequeno");
else if (num < 100)
    alert("Médio");
else
    alert("Grande");

Este programa vai primeiramente checar **se num é menor que 10**.

**Comment by ericdouglas** [comment]
@leresche obrigado!
