### ISSUE TITLE
[3rd] Tradução Cap. 5 - "Higher-order Functions"

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#404]
Responsável: @larismourullo

**Comment by joaostein** [comment]
@larismourullo, estou enviando essa mensagem para todos os responsáveis apenas para checar se está tudo certo com a sua tradução.  Se precisar de qualquer coisa, só avisar.

_ps. A data da [milestone](https://github.com/braziljs/eloquente-javascript/milestone/2) para finalizar a tradução está para 24 de Dezembro (ho-ho 🎅🎁).  Se você achar que não for realista, só avisar, ok?_

**Comment by larismourullo** [comment]
@joaostein opa, tudo certo sim, devo logo mais começa-la.

**Comment by joaostein** [comment]
@dulcetti você está interessado apenas na correção do que será traduzido, ou em traduzir também?
@larismourullo poderia nos dar um update na tradução?

**Comment by larismourullo** [comment]
@joaostein falta bem pouco pra terminar, logo mais estarei enviando o PR.

**Comment by dulcetti** [comment]
@joaostein como a @larismourullo está finalizando, pode deixar a tradução com ela e depois posso fazer as correções ;)

**Comment by larismourullo** [comment]
@dulcetti @joaostein tradução feita, estarei no aguardo dos feedbacks 👍

**Comment by joaostein** [comment]
valeu, @larismourullo! 🙌🎉

@dulcetti, fiz uma revisão inicial e, se observar qualquer melhoria, é só enviar um PR.

**Comment by joaostein** [comment]
@larismourullo, se quiser pegar outros capítulos, é só avisar na #387, beleza?
