### ISSUE TITLE
[3rd] Tradução Cap. 8 - "Bugs and Errors"

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#407]
Responsável: @cassiofariasmachado

**Comment by joaostein** [comment]
@cassiofariasmachado, estou enviando essa mensagem para todos os responsáveis apenas para checar se está tudo certo com a sua tradução.  Se precisar de qualquer coisa, só avisar.

_ps. A data da [milestone](https://github.com/braziljs/eloquente-javascript/milestone/2) para finalizar a tradução está para 24 de Dezembro (ho-ho 🎅🎁).  Se você achar que não for realista, só avisar, ok?_

**Comment by cassiofariasmachado** [comment]
Certo, vou iniciar a tradução.
