### ISSUE TITLE
[3rd] Tradução Cap. 12 - "Project: A Programming Language"

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#411]
Responsável: @emanuelgsouza

**Comment by joaostein** [comment]
@emanuelgsouza, estou enviando essa mensagem para todos os responsáveis apenas para checar se está tudo certo com a sua tradução.  Se precisar de qualquer coisa, só avisar.

_ps. A data da [milestone](https://github.com/braziljs/eloquente-javascript/milestone/2) para finalizar a tradução está para 24 de Dezembro (ho-ho 🎅🎁).  Se você achar que não for realista, só avisar, ok?_

**Comment by joaostein** [comment]
@emanuelgsouza - poderia dar um update e qual o seu plano para tradução deste capítulo?

**Comment by emanuelgsouza** [comment]
Fala @joaostein , tudo bem? Rapaz, gostaria de inicialmente me desculpar por essa demora absurda, e o que eu posso te garantir, é que essa tradução irá sair neste mês de Maio/2020. Tudo bem?

**Comment by joaostein** [comment]
Olá, @emanuelgsouza! Tudo bem, sem problemas. Nesse meio tempo, se precisar de qualquer coisa, é só me chamar que vamos conversando. Se cuida e grande abraço!

_ps. mudei o status para "em tradução"_

**Comment by emanuelgsouza** [comment]
Obrigado, igualmente!
