### ISSUE TITLE
Projeto Continua?

### ISSUE THREAD

**Issue by Morette** [braziljs/eloquente-javascript#427]
Olá pessoal,
este projeto ainda está de pé?

Pensei que iria ver mais PRs...

Estão guardando para liberar toda a tradução junta?

**Comment by joaostein** [comment]
Fala, @Morette.

Projeto ainda está de pé.

Sobre a sua pergunta, cada pessoa ficou responsável por gerenciar um capítulo.

(_se quiser ver a lista completa, é só olhar na #387_)

Sempre que PRs são enviados, eles são revisados e adicionados no branch da 3ª edição.

Quando a tradução estiver finalizada, deixaremos o branch da 3ª edição como principal.

Na sequência, arquivaremos o branch da 2ª edição apenas para deixar como referência.

Por ser um projeto colaborativo, a participação é espontânea de quem tem interesse em ajudar.

Assim, vamos precisar da ajuda de todos que estiverem dipostos a traduzir.

Vejo que você ficou responsável pelo Capítulo 10 e já fez um PR com tradução até a linha 363.

Muito obrigado 🖤

De pouquinho e pouquinho chegamos lá!

Se precisar de ajudar com qualquer coisa, é só avisar, ok?
