### ISSUE TITLE
Erro em link no 00-introducao.md e 18-formularios-e-campos-de-formularios.md

### ISSUE THREAD

**Issue by zignd** [braziljs/eloquente-javascript#432]
Após alguns esclarecimentos do @joaostein, estou atualizando a issue então para relatar que vários links do `00-introducao.md` estão quebrados e que links do `18-formularios-e-campos-de-formularios.md` estão fora do padrão do livro que é a utilização de paths relativos.

---

### Versão anterior da Issue:

~~No final da linha 158 temos o seguinte:~~

```
O [segundo projeto](./chapters/pratica-linguagem-de-programacao.md) conclui a primeira parte do livro.
```

~~O link está quebrado, mas usando o original como base, a intenção era apontar para o `./chapters/11-pratica-linguagem-de-programacao.md`.~~

**Comment by joaostein** [comment]
Obrigado, @zignd!

Dei uma olhada e existem 12 ocorrências similares com links quebrados no capítulo de introdução.

Todos os caminhos que contêm `./chapters/<path>` estão quebrando.

_(além do caso específico que você pontuou)_

Veja a foto:

![](https://dad6pq311uj47.cloudfront.net/items/2Y2s1D3e2W0J0G0A0M0d/Image%202019-04-06%20at%206.05.36%20PM.png)

**Comment by zignd** [comment]
Olá @joaostein! Fiz uma verificação aqui no meu clone com o seguinte comando:

```
grep -ri -P "chapters\/\D"
```

Para trazer apenas os links que após "chapters/" têm algo que não é um digito e retornou duas ocorrências para mim.

![Imgur](https://i.imgur.com/Jj6b3R2.png)

Posso corrigir essas duas então?

**Comment by zignd** [comment]
Opa, entendi agora, o problema está em ter "chapters" no path, isso acaba duplicando o termo do path durante a visualização pelo GitHub

**Comment by joaostein** [comment]
Sem problemas, @zignd!

**Comment by zignd** [comment]
Atualizei a issue @joaostein, para contemplar isso e também para incluir o que acabei de identificar no capítulo 18. Que tem links apontando para outros capítulos utilizando uma URL completa.

**Comment by joaostein** [comment]
claro, já está merged! obrigado pela contribuição!
