### ISSUE TITLE
Próxima página

### ISSUE THREAD

**Issue by juliosaraiva** [braziljs/eloquente-javascript#435]
Acho que no final de cada capítulo, pode ser adicionado um link para a próxima página. Assim fica mais dinâmico para interagir com o livro.

**Comment by joaostein** [comment]
@juliosaraiva obrigado pela sugestão. se quiser enviar um PR, podemos considerar a inserção da melhoria. vou fechar apenas para manter as issues limpas e focadas na tradução da terceira edição.
