### ISSUE TITLE
Falta um capítulo na versão PDF

### ISSUE THREAD

**Issue by jos3s** [braziljs/eloquente-javascript#442]
Na versão PDF do livro, consta no sumário o capítulo "Introdução", capítulo este que possui sua versão em markdown, mas não está disponível na versão PDF do livro. Essa é uma escolha pretendida?

**Comment by joaostein** [comment]
@jos3s o suporte às atualizações é feito apenas nos arquivos `.md`. Se você quiser a versão PDF ou Epub/mobi do livro, você pode utilizar alguma [ferramenta de conversão](https://pandoc.org/) e gerar uma versão para seu uso exclusivo. #347
