### ISSUE TITLE
Dúvida sobre as traduções

### ISSUE THREAD

**Issue by raphaelkieling** [braziljs/eloquente-javascript#454]
Estou começando as traduções do capítulo 3. Mas algumas dúvidas:
- Irei basear minha tradução já na terceira edição? (só pra confirmar)
- Crio uma branch a partir de master mesmo? E depois faço pull request da minha `traducaoCap3` pra `master` daqui?
- Os textos que estão sendo traduzidos são os que já existiam da 2º edição para 3º?

Não entendi exatamente o fluxo de vocês hoje. Peço desculpas pelas dúvidas básicas mas quero evitar de começar a traduzir e depois ver que não era o lugar correto kk

**Comment by joaostein** [comment]
> Irei basear minha tradução já na terceira edição? (só pra confirmar)

Existem duas versões do livro: “2ª edição” e “3ª edição”. A tradução da segunda edição já está finalizada. Por isso, o trabalho da issue #402 é referente ao capítulo 3 da terceira edição.

> Crio uma branch a partir de master mesmo?

A _branch_ `master` possui a tradução da segunda edição. Por isso, para trabalhar na terceira edição, você deverá criar uma _branch_ de `3rd`. É interessante você verificar/atualizar o arquivo original em inglês para certificar que está trabalhando na versão mais atualizada do arquivo (a última atualização de arquivo `03_functions.md` foi atualizada em Nov 14, 2018).

> E depois faço pull request da minha traducaoCap3 pra master daqui?

Você fará um _pull request_ para `3rd` (3ª edição). No `master` está a tradução da 2ª edição.

> Os textos que estão sendo traduzidos são os que já existiam da 2º edição para 3º?

Você traduzirá os arquivos originais em inglês da 3ª edição do livro. Tudo que for relacionada à 2ª edição já está finalizado.

Se algum ponto ainda estiver confuso ou tiver mais dúvidas, é só me avisar que vamos conversando. Para facilitar e centralizar a comunicação, sugiro que mande as dúvidas direto na #402.
