### ISSUE TITLE
Como traduzir "Creating new words in prose is usually bad style"

### ISSUE THREAD

**Issue by raphaelkieling** [braziljs/eloquente-javascript#455]
Não achei um jeito muito legal de traduzir:
```
Creating new words in prose is usually bad style
```
Tentei traduzir algo como:
```
Criando novas palavras em prosa é normalmente um estilo ruim.
```

Só que `prosa` não me parece a melhor forma, tentei ver alguns dicionários online e não me veio nada a mente. Alguma ideia?

**Comment by manoelbjr** [comment]
Oi Raphael, informa o contexto e/ou o trecho que está escrito.

Podemos sugerir um sinônimo.

**Comment by manoelbjr** [comment]
Quem tal:

`Criar novas palavras é um discurso é, normalmente, um estilo ruim.`

**Comment by raphaelkieling** [comment]
Sim faz total sentido criar palavras "soltas" realmente não faz sentido em um discurso/prosa é ruim mas na programação realmente é importante. Show acho que vou manter assim então, o que acha?

```
A aplicação mais óbvia de funções é definir novos ((vocabulary)). Criando novas palavras em um discordo é, normalmente, um estilo ruim. Mas na programação, é indispensável.
```

**Comment by joaostein** [comment]
Existem muitas similaridades no terceiro capítulo entre as versões 2 e 3 do livro.

A tradução na segunda versão do livro saiu assim:

> A aplicação mais óbvia das funções é quando queremos definir novos vocabulários. Criar novas palavras no nosso dia a dia geralmente não é uma boa ideia, porém em programação é indispensável.

referência: https://github.com/braziljs/eloquente-javascript/blob/master/chapters/03-funcoes.md

Lembre-se de que existem casos em que é possível adaptar a tradução para fazer sentido para o leitor. 

Existem casos em que, se traduzir ao "pé da letra", perde o sentido ou deixa a leitura confusa após traduzir.

**Comment by raphaelkieling** [comment]
Tu tem razão, ótima tradução
