### ISSUE TITLE
Codigos do Capítulo 15 estão desatualizados 

### ISSUE THREAD

**Issue by Canturilsnaik** [braziljs/eloquente-javascript#458]
Os códigos do capítulo 15 estão desatualizados, no site do eloquente ja se encontra com Class mas no capítulo 15 estão com escritos com ´function´ fora que no site oficial esta de um jeito e no capítulo o codigo esta de outro jeito 🙅‍♂️

**Comment by joaostein** [comment]
Olá, @Canturilsnaik! existem duas versões do livro (segunda e terceira edições). O branch `master` possui a segunda versão traduzida, que pode ser encontrada no site oficial [aqui](https://eloquentjavascript.net/2nd_edition/15_game.html). A versão que você olhou no site oficial e que utiliza `Class` é a terceira versão do livro, que está em tradução no momento no branch `3rd`. Se quiser contribuir, sugiro que dê uma olhada na #387.
