### ISSUE TITLE
Cap. 17 - HTTP

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#54]

**Comment by fsbatista** [comment]
Vou fazer esse. Esse fds fica pronto!

**Comment by ericdouglas** [comment]
Ótimo @fsbatista ! :smile:

**Comment by rafaelcfreire** [comment]
Olá @ericdouglas e @fsbatista 
Vi que esse capítulo está parcialmente traduzido, tenho disponibilidade para finalizar o mesmo. Posso? Ou o @fsbatista ainda está trabalhando nele?

Obrigado,

**Comment by ericdouglas** [comment]
@rafaelcfreire vamos aguardar até amanhã a resposta do @fsbatista tudo bem?

**Comment by rafaelcfreire** [comment]
Olá pessoal,

Considerando que o @fsbatista não se manifestou, assumirei a finalização do capitulo 17. 
@ericdouglas , obrigado pelo convite. Participarei sempre que possível no restante das traduções/correções

**Comment by ericdouglas** [comment]
@rafaelcfreire show! Manda ver cara :wink:

**Comment by fsbatista** [comment]
Boa!

**Comment by ericdouglas** [comment]
Os exercícios deste capítulo precisam ser finalizados.

Adicionar alterações na branch `master` e `gh-pages`

**ps**: deixei essa nota aqui só para me lembrar do que precisa ser feito :smile:

**Comment by joaostein** [comment]
@ericdouglas Estou repassando esse capítulo.  Em breve chegarei na parte dos exercícios, daí só precisamos passar para o site para matar essas pendências :+1:

**Comment by ericdouglas** [comment]
@joaostein perfeito! :smile:
