### ISSUE TITLE
Cap. 19 - Projeto: Um Programa de Pintura

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#56]

**Comment by adrianotadao** [comment]
@ericdouglas vou traduzir esse capitúlo, okay?

**Comment by ericdouglas** [comment]
Ok @adrianotadao ! = )

**Comment by SauloSilva** [comment]
Irei passar este para o site

**Comment by ericdouglas** [comment]
@SauloSilva já iniciou a passar? Se não, pode deixar que eu faço amanhã e ai finalizamos essa parte de publicar os capítulos já traduzidos. :smile:

**Comment by SauloSilva** [comment]
@ericdouglas done.

**Comment by ericdouglas** [comment]
@SauloSilva :+1:
