### ISSUE TITLE
Alterar nome do repositório

### ISSUE THREAD

**Issue by randsonjs** [braziljs/eloquente-javascript#66]
Seria interessante alterar o nome do repositório para `eloquent-javascript` ao invés de `eloquente-javascript`. Ficando assim com o nome original!

O que acham?

**Comment by ericdouglas** [comment]
@randsonjs por mim tudo bem. No caso deve ser algum `owner` para fazer isso.

cc/ @zenorocha @joaostein

**Comment by zenorocha** [comment]
Acabei de colocar vocês como owners ;)

**Comment by ericdouglas** [comment]
@zenorocha vlw! 

@randsonjs já existe um outro repo com esse nome na org, não temos como mudar para esse proposto por você.

Poderia ser `javascript-eloquente`, mas não vejo necessidade de mudar.

**Comment by lucasfcosta** [comment]
Acho que `javascript-eloquente` seria um bom nome visto que é uma tradução mais adequada do título do livro.

**Comment by gabrielfgularte** [comment]
Se o merge entre o meu repo e esse for bem sucedido, podemos apagar ele aqui da org e pegar o nome dele, que na verdade, é o Fork do projeto original do livro (Eloquent-Javascript). ;)

**Comment by zenorocha** [comment]
Exatamente, qual vocês acham que deve ser o repositório definitivo e por que?

**Comment by ericdouglas** [comment]
@lucasfcosta sim, fica melhor mesmo, isso é inegável hehe ;D

@gabrielfgularte +1!

Podemos trabalhar com esse objetivo, manter da forma que está, e depois alterar em definitivo o nome deste repositório para `Eloquent-Javascript`.

@zenorocha penso que este repositório seja melhor para centralizar os arquivos pois conseguimos criar issues, no do @gabrielfgularte isso não é possível.

**Comment by zenorocha** [comment]
@ericdouglas isso não é problema, já ativei as issues daquele repo.

**Comment by ericdouglas** [comment]
@zenorocha legal! 

Como estão imaginando fazer um merge entre os repos? Na verdade, acho que vão ficar dois repos distintos mesmo, usando a tradução deste para atualizar os arquivos do repo do @gabrielfgularte .

Dessa forma, podemos alterar o nome desse repositório para `javascript-eloquente`, para ser mais agradável aos olhos, e o outro continua da forma que está.

**Comment by lucasfcosta** [comment]
Estive dando uma olhada no repositório do @gabrielfgularte e a estrutura lá está bem diferente daqui, na verdade neste projeto estamos traduzindo os capítulos e criando assim arquivos .md, lá os arquivos .txt são montados para gerar .pdf, .epub etc...

Para fazer o merge seria necessário portar nossos arquivos markdown para corresponderem aos arquivos que vão ser montados lá. Talvez fosse mais interessante usar o GitHub Pages para servir nossos arquivos .md usando Jekyll.

**Comment by gabrielfgularte** [comment]
Gostei da ideia do @ericdouglas . Podemos continuar com a tradução aqui e ir jogando para o meu repo. Depois de pronta, movemos ele pra cá de vez. :)

**Comment by randsonjs** [comment]
Cara, eu perguntei isso na outra [discussão](https://github.com/braziljs/ideias/issues/6). 

Quanto ao nome, não alteraria para outros porque o nome do livro é Eloquent Javascript. Alterar nome deixaria confuso.

Quanto ao outro repositório, acho que não precisamos trabalhar com dois repositórios. Porque não criar uma branch para isso?

Sem falar que já fiz o website e está servindo os arquivos em markdown estáticos. Se continuar dessa forma não precisa alterar nada. Apenas passo o website para a branch `gh-pages`. 

Tem que ver isso porque o @joaostein achou melhor deixar da forma original do site, então teriamos o trabalho de pegar as traduções em markdown e transformar para `.txt` para geração de `.pdf`, `.epub`, etc...

Na minha opinião. Prefiro mudar o website para a branch `gh-pages` em jekyll e ir adaptando, até porque já tem muita coisa pronta. Mas se o desejo da maioria for deixar conforme o original não tenho problemas quanto a isso ;) Só avisando que vai dar muito retrabalho.

**Comment by ericdouglas** [comment]
@randsonjs eu sou a favor de fazermos tudo com base em `.md`, tradução, site, `.pdf` e demais formatos.

O site está excelente, realmente não tem porque ter esse retrabalho.

**Comment by joaostein** [comment]
Fala galera, respondendo algumas dúvidas levantadas aqui:

Existem dois repositórios: [[1]] iniciado pelo @ericdouglas e [[2]] iniciado pelo @gabrielfgularte. O repo [[1]] usa uma estrutura totalmente diferente da usada no livro original.  Em [[1]] estamos usando `markdown` e temos uma estrutura de arquivos bem “lean”, o que nos permite uma série de coisas interessantes (como a integração com o site que o @randsonjs fez e uma organização melhor dos arquivos).  Em [[2]], temos um fork do repositório original com todos os arquivos que são necessários para termos uma versão nos padrões da editora e do autor do livro (inclusive para fazer a build do livro em vários formatos).  Em [[2]], temos arquivos `.txt` que nada mais são do que arquivos [asciidoc](http://asciidoctor.org/docs/what-is-asciidoc/), um formato usado por uma série de autores de livros.  Por esse motivo, é bastante importante seguirmos as orientações passadas pelo autor em termos um repo oficial da tradução que seja um ***“fork-and-edit”*** e que seja possível usar a toolchain do autor que é o caso do [[2]].  Isso não impede que façamos o trabalho utilizando toda a estrutura que já temos em [[1]] e usar `markdown`.  O mais importante é não perdemos o prazer e estarmos nos divertindo com um projeto que vai contribuir para a comunidade JavaScript, ajudando pessoas que não tem condições de consumir o livro em inglês :)

Nós podemos fazer um brainstorm de ideias aqui para acharmos a melhor solução para essa situação, o que acham?

A princípio, uma forma simples que vejo para conseguirmos atingir nosso objetivo, seria transportando os capítulos que forem sendo finalizados em [[1]] para [[2]], convertendo-os de `markdown` para `asciidoc`, sem afetar em nada o repo [[1]]. 

Eu entendo que em um primeiro momento parece ser retrabalho transformar `markdown` para `asciidoc`, tendo em consideração que se usarmos os arquivos em markdown, podemos ter o site e o livro da mesma maneira. Entretanto essa é mais uma questão com o autor e editora. Alguém tem mais ideias de como poderíamos fazer isso de uma maneira melhor e mais eficiente?

cc @ericdouglas @randsonjs @gabrielfgularte @letanure @SauloSilva @fsbatista @lucasfcosta @leonascimento @vitorbritto @mazulo @danilovaz @zenorocha -- estou pingando a galera que se mostrou interessada e a galera que já participa do projeto de alguma forma. Se souberem de alguém que não marquei aqui, poderiam chamá-los?


[1]: https://github.com/braziljs/eloquente-javascript (eric)
[2]: https://github.com/braziljs/Eloquent-JavaScript (gabriel)

**Comment by fsbatista** [comment]
Eu acho que existe um valor imenso em deixar o repo compatível com a estrutura original do livro, por isso concordo com a conversão do markdown para asciidoc. Acho que da pra ir traduzindo e na medida que os capitulos sao revisados nos podemos ir convertendo para asciidoc.

**Comment by ericdouglas** [comment]
@joaostein @fsbatista podemos então focar primeiro os esforços na tradução e revisão do livro nos arquivos `.md`, e depois vamos para o formato original do livro.

O que acham?

**Comment by gabrielfgularte** [comment]
Eu acho perfeito. Traduzimos no repo [[1]](https://github.com/braziljs/Eloquent-JavaScript) e depois colocamos a tradução no repo [[2]](https://github.com/braziljs/Eloquent-JavaScript)

@joaostein os links [2] e [1] no teu comentário ficaram iguais. Dá uma editada aí pq pode confundir a galera. ;)

**Comment by mazulo** [comment]
Também concordo com a maneira que o @fsbatista e @ericdouglas falaram. Podemos ter 2 grupos, onde um estaria tratando da tradução/revisão dos capítulos, enquanto o outro já iria convertendo os capítulos já traduzidos/revisados para `asciidoc`.

**Comment by danilovaz** [comment]
Bom, gostaria só de fazer uma observação no nome. Tendo em vista que estamos falando de uma tradução de um livro, eu acho o mais correto traduzir para Javascript Expressivo.

O título carrega uma palavra técnica e uma palavra "normal", no caso **eloquent**, porém a tradução **eloquente** não me parece a mais correta porque muitas pessoas terão dificuldades com o título. E como eloquent não é um termo técnico, não vejo problema em ser traduzido. 

Para tanto, eu indico utilizar a palavra **expressivo** que é sinônimo de **eloquente** porém com significado muito mais ~~expressivo rs~~ forte e utilizado no vocabulário geral.

**Comment by lucasfcosta** [comment]
Concordo com o @ericdouglas e o @fsbatista  , seria bem interessante termos os dois formatos disponíveis. Aliás, se eu não me engano, dá pra fazer a conversão com o [Pandoc](http://johnmacfarlane.net/pandoc/), poupando bastante trabalho.

**Comment by ericdouglas** [comment]
@lucasfcosta +1 !

**Comment by SauloSilva** [comment]
@lucasfcosta +1, eu concordo em continuar fazendo em markdown depois utilizar um conversor para fazer os txt automaticamente.
Também acho que o ideal é manter tudo isso em um único repositório, visando a praticidade.

**Comment by randsonjs** [comment]
Sim, apenas em um repositório. Eu forkei o repositório do @gabrielfgularte e coloquei em uma branch chamada `official`. Todas as alterações deverão ser feita nessa branch. Ela não tem nenhuma relação com a `master`.

Isso evita de ter dois repositórios. Apenas um com o mesmo nome é suficiente ;)

Questão do nome, não é bom trocar não não em. É melhor deixarmos igual o nome do livro. Se não vai ficar parecendo aqueles filmes que a tradução não tem nada a ver. Sem falar que é o nome do livro.

Se precisarem mexer no outro repositório, por favor mexam nesse na branch `official`. Para mantermos um padrão e mexermos em apenas um lugar. Depois que toda a tradução estiver pronta veremos como irá ficar o website.

**Comment by ericdouglas** [comment]
@randsonjs +1 sobre o nome kkkk Verdade cara! rs

**Comment by randsonjs** [comment]
HAHAHA

Então, minha sugestão é deletar aquele repositório e deixar tudo nesse. E depois alterar o nome desse para `eloquent-javascript` que é o nome dele ;)

Quem apoia?

**Comment by joaostein** [comment]
Eu sou super tranquilo quanto ao nome.  Em relação a dois repositórios ou um, eu preciso verificar com o autor quanto a isso. Pelas conversas, ele deixou claro para irmos na direção de um "fork-and-edit" no trabalho final usando uma convenção de internacionalização em um branch (i18n/pt_br). Não sei se ter um repo que não siga esse padrão seja alguma problema, apenas preciso verificar. Afinal estamos trabalhando diretamente em um projeto que "faz parte" de um trabalho maior que foi iniciado pelo próprio autor quando escreveu o livro, e nada mais justo seguirmos as orientações dele, o que acham? :)

**Comment by gabrielfgularte** [comment]
@joaostein +1

**Comment by ericdouglas** [comment]
@joaostein penso que temos que analisar a forma que vamos ter o melhor resultado e da forma mais rápida.

A licença do livro nos permite trabalhar da forma que quisermos, desde que não tenhamos fins comerciais com esse conteúdo.

O problema da tradução estar no repositório original é que isso pode acarretar um grande trabalho para o autor, pois imagina se em cada país alguém for criar uma tradução e enviar para o repo original? Além do trabalho de aceitar os PR's, o autor não tem competência para avaliar se o que foi submetido, em outra língua, está melhor do que o que foi feito.

A minha opinião é que as traduções devem estar em um repositório a parte, e no original apenas teria uma referência, para que alguém não comece uma nova tradução.

**Comment by ericdouglas** [comment]
ps: só tem sentido ter os arquivos traduzidos no repo original se o autor adicionar colaborados de cada língua, e quando houver PR

**Comment by joaostein** [comment]
@ericdouglas — concordo 100% com você. temos que utilizar a forma na qual vamos ter a maior produtividade possível para terminarmos isso e liberarmos o conteúdo para as pessoas que não tem condições de ler em inglês. Por isso optamos por continuar com o markdown (já que todos estão acostumados, e não faz sentido adicionarmos uma barreira — asciidoc — nesse estágio impedindo que o projeto tenha a mesma fluência). O asciidoc virá como uma complemento do projeto visando uma tradução uniforme seguindo os padrões do livro original.

Sobre a confusão a respeito da tradução estar ou não no repositório original — A tradução estará em um repositório em baixo da BrazilJS foundation e terá uma referência no wiki do repositório original e você é o mantenedor desse processo atual de tradução. Se por algum motivo não for possível ter uma manutenção frequente, por favor nos informe o quanto antes para que podemos lidar com isso da melhor maneira.

No mais, vamos focar mais em “getting shit done” do que em burocracia, o que acha?

**Comment by ericdouglas** [comment]
Ótimo @joaostein !

> "A tradução estará em um repositório em baixo da BrazilJS foundation e terá uma referência no wiki do repositório original."

Perfeito! Assim fica excelente!

Pode deixar que é possível que eu mantenha o projeto! :smile:

Vamos finalizar essa thread aqui então:

- esse repositório terá a tradução em `.md` e o branch `gh-pages`.
- no repositório do @gabrielfgularte teremos a versão asciidoc, e a wiki no repositório original irá apontar para o repositório *forkado*.

Algo mais para fecharmos essa issue?

**Comment by joaostein** [comment]
@ericdouglas -- acho que os pontos são esses mesmo
