### ISSUE TITLE
Convenções para a realização das traduções

### ISSUE THREAD

**Issue by fsbatista** [braziljs/eloquente-javascript#67]
Acredito que seria interessante fazer uma espécie de glossário com os termos em inglês mais importantes encontrados no livro e suas respectivas traduções. Deste modo fica mais fácil uniformizar as traduções e revisões deste repo. O que acha @ericdouglas ?

**Comment by ericdouglas** [comment]
Perfeito @fsbatista , concordo! Inclusive discutimos sobre isso [aqui](https://github.com/braziljs/eloquente-javascript/pull/65).

Vou atualizar o readme com o que ficou decidido.

Creio que um glossário seja um pouco complicado. Prefiro apostar no bom senso do tradutor, e caso tenha alguma dúvida, este pode comentar na issue referente do capítulo que está traduzindo pedindo auxílio.

O que acha?

**Comment by fsbatista** [comment]
Minha preocupação é termos várias traduções para um mesmo termo técnico, o que pode prejudicar a compreensão do livro. Por isso, ao deixar-mos em um .md separado, os principais termos técnicos da tradução, teremos uma guia na hora de traduzir e revisar os trabalhos. De qualquer forma, se eu começar a notar muitas traduções diferentes para um mesmo termo, eu posto um issue aqui!

**Comment by letanure** [comment]
:+1:

**Comment by ericdouglas** [comment]
Ok @fsbatista ! Se ver que isso está ocorrendo, podemos criar este glossário. 

No momento acho mais interessante focarmos em traduzir, pois para a criação efetiva desse glossário, teremos que mapear o livro todo para encontrar esses termos, além de engessar um pouco na tradução.

Na revisão creio que conseguimos lapidar bem também. = )

**Comment by joaostein** [comment]
Concordo com @fsbatista.  É uma ótima ideia termos um local onde podemos colocar convenções para seguirmos nas traduções. Um ótimo lugar para isso pode ser uma página na wiki sendo linkada no readme.

Por exemplo:
* Escrever números usando numerais ou extenso? (2 ou dois)
* Utilizar o formato Americano ou Brasileiro nos números? (20,000 ou 20.000 ou 20000)
* Traduz blocos de código ou não?
* etc

Essas foram algumas coisas que vieram em minha mente porque me deparei com elas fazendo a revisão do capítulo 3.  Com certeza tem mais coisas que podem ser documentadas como "convenções".  Além disso, essa ideia de catalogarmos alguns termos pode ser interessante também e não há necessidade de que isso seja feito de uma maneira que impeça o andamento das traduções. Pode ser um documento orgânico que vai sendo atualizado/discutido a medida que novos termos forem sugeridos (pessoas que estão revisando/traduzindo irão eventualmente se deparar com isso, e se acharem necessário, podem sugerir novos termos, descartando a hipótese de termos que mapear o livro todo gerando um gargalo).

@ericdouglas eu e o @fsbatista podemos nos encarregar de criar essa estrutura, o que acha? Assim não bloqueamos ninguém de continuar traduzindo/revisando.

**Comment by randsonjs** [comment]
O que acha melhor para isso @joaostein? Uma página wiki seria o ideal?

**Comment by joaostein** [comment]
A primeira solução que me veio a cabeça seria uma página wiki chamada "Convenções para tradução" ou algo do tipo e termos apenas uma menção no README com um link.  Dessa forma mantemos o README limpo e ao mesmo deixando acessível essa informação para quem precisar.  Se tiverem outras ideias acho super válido conversamos sobre para chegar em um solução que resolva o problema :)

**Comment by ericdouglas** [comment]
@joaostein acho super válido criar o documento de forma paralela, pois assim não paramos com os trabalhos aqui.

Outro bônus para esse glossário, é que o mesmo poderá servir não só para esse projeto, mas para todos os futuros projetos de tradução da comunidade : )

Se puderem estruturar essa parte, será ótimo, e posteriormente todos nós tradutores e revisores podemos ir acrescentando termos de acordo com a demanda, bem orgânico mesmo, da forma como você falou.
