### ISSUE TITLE
Cap.01 - Valores, Tipos e Operadores

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#7]
Tradução do arquivo [01-valores-tipos-operadores.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/01-valores-tipos-operadores.md)

**Comment by adrianoavelino** [comment]
Encontrei uma diferença no operador do texto original em **Valores Booleanos > Comparações**:

_"Outros operadores similares são >= (maior que ou igual a), <= (menor que ou igual a), == (igual a) e **!==** (não igual a)."_

No original o operador é **!=**:

_"Other similar operators are >= (greater than or equal to), <= (less than or equal to), == (equal to), and **!=** (not equal to)."_

_OBS: Essa é minha primeira issue, caso esteja fazendo algo errado me comuniquem_

**Comment by SauloSilva** [comment]
@adrianoavelino esta errado mesmo.
Você poderia contribuir com esta correção?

Ficaremos felizes em receber um Pull Request seu (=

**Comment by randsonjs** [comment]
Estamos esperando sua contribuição @adrianoavelino! :)

Muito obrigado por nos avisar! :smile:

**Comment by adrianoavelino** [comment]
Feito. Com certeza deva ter feito algo errado, mas procurei fazer como "Como contribuir" da home

**Comment by SauloSilva** [comment]
@adrianoavelino ficou certo. Muito obrigado.
