### ISSUE TITLE
Sugestão para workflow das traduções/revisões

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#73]
Acredito que podemos ser um pouco mais rigorosos nesse sentido.  Se formos analisar um sistema tradicional de taquigrafia por exemplo, temos os seguinte workflow:

1. Existe um setor chamado "apanhamento". Esse setor é responsável por "apanhar" o conteúdo inicial de uma fonte externa (no caso discursos, palestras etc), e criar a primeira versão do documento tentando ao máximo produzir um documento próximo de um trabalho final e aceitável (aqui inclui pesquisas, erros básicos de português, convenções, etc). Entretanto sabemos que sempre passam detalhes.
2. Por isso, existe um outro setor chamado "revisão".  O dever da “revisão” é receber o trabalho do “apanhamento” e entregar um trabalho final aceitável (muitas vezes o apanhamento já entrega um trabalho perfeito havendo pouca ou nenhuma necessidade de alteração, mas as vezes acaba passando erros, falta de pesquisa etc…). Nesse ponto, teoricamente temos o documento final. Sempre é bom haver uma verificação final a cargo de ter ao menos uma segunda opinião sobre o documento final.
3. Por isso, existe um último setor chamado "supervisão". Esse setor é responsável por receber o trabalho teoricamente pronto da "revisão" e fazer pequenos ajustes que possam ter passado despercebidos (como detalhes de convenção, formas de escrita, etc). Esse setor recebe praticamente o trabalho pronto da "revisão" e só tem que dar um “check” para dizer que o trabalho está 100%.

O nosso workflow hoje contempla apenas os dois primeiros setores. Acredito que poderia ser uma boa ideia termos um outro passo após a revisão e abrirmos a oportunidade de termos uma segunda revisão (supervisão), a fim de termos uma segunda opinião sobre a revisão e ao mesmo tempo achar eventuais erros que passarem da revisão. Vai dar um pouco mais de trabalho, porém acredito que assim podemos ter a oportunidade de produzir um material de maior qualidade. O que acham?

**Comment by ericdouglas** [comment]
Fica excelente assim @joaostein , podemos adicionar as labels `aguardando supervisão` e `supervisão` no nosso fluxo atual.

Dessa forma vamos conseguir ter um resultado super profissional, e esse projeto merece isso.

Vamos aguardar para ver se alguém tem alguma objeção. Caso não haja, criamos as labels e atualizamos o README, explicando esse novo processo.
