### ISSUE TITLE
Transferir website

### ISSUE THREAD

**Issue by randsonjs** [braziljs/eloquente-javascript#76]
Estou pensando em mudar o website aqui nesse repositório.

Como ele é feito em jekyll, no caso é só criar uma branch orfã. Dessa forma centralizamos tudo nesse repositório.

O que acham?

**Comment by ericdouglas** [comment]
Penso ser o ideal mantermos tudo relacionado aos arquivos `.md` nesse repo @randsonjs !

Concordo com a transferência!

**Comment by SauloSilva** [comment]
@randsonjs +1

**Comment by joaostein** [comment]
@randsonjs -- dei assign nessa task de criar o branch com os arquivos p/ você.

Qualquer dúvida pode dar um ping :)

**Comment by randsonjs** [comment]
Transferido ;)

**Comment by randsonjs** [comment]
Peço desculpa pela demora pessoal.

**Comment by joaostein** [comment]
Valeu @randsonjs. Não se preocupe com isso, a ideia é irmos fazendo a medida que formos tendo tempo livre mesmo, sem stress :smile:

**Comment by ericdouglas** [comment]
@randsonjs show! :smile:
