### ISSUE TITLE
Cap.02 - Estrutura do Programa

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#8]
Tradução do arquivo [02-estrutura-do-programa.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/02-estrutura-do-programa.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/02_program_structure.html)

**Comment by adrianoavelino** [comment]
O bloco de código da linha 430´(Enviando um Valor com `switch`) `case "rainy"` está como o texto original, porém algumas palavras foram traduzidas.

**Comment by SauloSilva** [comment]
@adrianoavelino realmente, se quiser arrumar e aproveitar para fazer uma revisão deste capítulo por completo, fique a vontade. Como tu já deve ter visto, temos um [manual](https://github.com/braziljs/eloquente-javascript/blob/master/CONTRIBUTING.md#definições-para-termos-em-geral) que serve para os revisores. Qualquer coisa pode perguntar.

Ficaremos felizes com sua contribuição (=

**Comment by ericdouglas** [comment]
Galera, vamos iniciar os trabalhos neste capítulo seguindo a metodologia sugerida na issue #176 .

Quem tiver interesse em participar, favor manifestar aqui nessa issue para sabermos exatamente em quantas partes vamos dividir o capítulo.

A divisão será basicamente assim:

- `Total de linhas do arquivo / Número de participantes`, arredondando para cada pessoa ficar com X partes do capítulo.

@braziljs/eloquent-javascript

**Comment by joaostein** [comment]
pode me colocar :)

**Comment by ericdouglas** [comment]
Fazendo a divisão entre @joaostein , @SauloSilva e eu, em ordem alfábetica, ficou dessa forma:

- **Total de linhas**: 555 (185 linhas para cada)
- @ericdouglas: Introdução até seção Fluxo de Controle
- @joaostein: Execução Condicional até Saindo de um Loop
- @SauloSilva: Atualizando variáveis Suscintamente até o fim

Lembrando que agora o processo é o de **revisão**.

Let's go! :construction_worker:

**Comment by SauloSilva** [comment]
:+1:

**Comment by joaostein** [comment]
Bora! :)

**Comment by SauloSilva** [comment]
@ericdouglas e @joaostein podemos dar como finalizado esta Issue? Ou vocês acham necessário uma supervisão?

**Comment by joaostein** [comment]
@SauloSilva — estou bem inclinado a ir fechando as issues antigas.  se houver melhorias/sugestões, podemos ir fazendo através de PRs específicos (erros de portugues, melhorias na forma de como foi traduzido, alteração de palavras, etc…).  dessa forma fica até mais fácil de outras pessoas contribuírem, pois remove qualquer tipo de burocracia e comentários que possam confundir alguém novo que esteja querendo ajudar.

Se quiserem manter um log para cada capítulo (similar ao que estamos fazendo hoje, através de indicação das referências nos PRs — ref #x), podemos ir reabrindo essas issues (a medida que formos terminando as revisões) e usá-las **apenas** para fazer referências, ficando mais fácil ver todos os PRs associados a cada capítulo e limpo de comments. Inclusive, podemos dar “[lock](https://help.github.com/articles/locking-conversations/)” nessas issues para garantir que não seja feito comments.

O que acham aqui? Alguma outra ideia/melhoria?

// cc @ericdouglas @gabrielfgularte @randsonjs @braziljs/eloquent-javascript

**Comment by ericdouglas** [comment]
@joaostein faz muito sentido! Podemos fazer isso sim.

**Comment by joaostein** [comment]
@ericdouglas -- já iniciei o processo das issues de capítulos que trabalhamos recentemente. a medida que formos avançando nos capítulos vamos atualizando as issues de log dos outros capítulos e fechando as antigas.
