### ISSUE TITLE
Cap.03 - Funções

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#9]
Tradução do arquivo [03-funcoes.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/03-funcoes.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/03_functions.html)

**Comment by joaostein** [comment]
@ericdouglas -- se importaria se eu pegasse a revisão desse capítulo?

**Comment by ericdouglas** [comment]
Opa, é todo seu @joaostein ! :smile:

**Comment by joaostein** [comment]
valeu meu querido, assim que finalizar dou um retorno :)

**Comment by joaostein** [comment]
Capítulo disponível para supervisão.  Um detalhe:  Há alguns labels "TODO" referentes a links que fazem sentindo quando o site estiver online.  Eu deixei passar porque não faz sentido adicionar os links agora já que não temos páginas para fazer a referência.

**Comment by ericdouglas** [comment]
@joaostein tranquilo! Faz todo sentido =)

**Comment by SauloSilva** [comment]
@joaostein tranquilo.

**Comment by SauloSilva** [comment]
Irei supervisionar este.

**Comment by SauloSilva** [comment]
@braziljs/eloquent-javascript após o merge do pull request #179 teremos o capítulo 03 pronto :smile:

**Comment by ericdouglas** [comment]
lol :tada: :clap: :clap: :clap:

**Comment by SauloSilva** [comment]
@randsonjs pode subir no site este capítulo fazendo favor?

**Comment by randsonjs** [comment]
Agora está [disponivel online \o/](http://eloquentjavascript.com.br/chapters/funcoes/)

**Comment by ericdouglas** [comment]
@randsonjs :tada: :tada: :tada: :smile:
