### ISSUE TITLE
Como vocês traduziriam o termo: "Let’s get coding"?

### ISSUE THREAD

**Issue by joaostein** [braziljs/eloquente-javascript#92]
Me deparei com esse termo revisando o #9 e não sei ao certo qual seria a melhor forma de traduzir.

O termo que usamos hoje é: "Vamos codar".  

Eu tenho a impressão de que o termo "codar" não é um termo válido na língua portuguesa, porém descreve perfeitamente o termo em inglês e ouço bastante pessoas falando dessa forma.  No português, o termo "codificar" representa bem a tradução, porém soa um pouco estranho: "Vamos codificar". 
```
codificar 
co.di.fi.car 
(lat codice+ficar2) vtd 1 Reduzir a código; reunir em código. 2 Coligir.
```

O que acham sobre isso, e qual maneira que faz mais sentido para vocês? Claro que outras alternativas são totalmente bem-vindas :)

**Comment by ewertonorg** [comment]
Eu usaria "Vamos codar".

**Comment by vitortalaia** [comment]
Também usaria "Vamos codar"

**Comment by ericdouglas** [comment]
Vamos *codar* :+1:  :+1:  :+1: 

Vamos programar :+1:  :+1: 

Vamos codificar :-1:

**Comment by gabrielfgularte** [comment]
Vamos codar então, fechado.

**Comment by ericdouglas** [comment]
boa @gabrielfgularte
