### ISSUE TITLE
Como vocês estão traduzindo o termo "callback"?

### ISSUE THREAD

**Issue by gabrielfgularte** [braziljs/eloquente-javascript#97]
- Função de retorno?
- Função de volta?
- ???

**Comment by ericdouglas** [comment]
@gabrielfgularte não lembro agora de ter passado por esse termo, mas acho interessante não traduzir essa palavra, apenas deixar em itálico acho que já seria o suficiente.

O que acham pessoal?

**Comment by ewertonorg** [comment]
Concordo com o @ericdouglas. A palavra callback é mais usada em artigos,livros e posts.

**Comment by joaostein** [comment]
:+1: em não traduzir termos técnicos

**Comment by randsonjs** [comment]
Mesmo aqui

**Comment by gabrielfgularte** [comment]
Blz

**Comment by ewertonorg** [comment]
:+1:
