### ISSUE TITLE
Como vocês estão traduzindo "threads"?

### ISSUE THREAD

**Issue by gabrielfgularte** [braziljs/eloquente-javascript#98]
Essa eu nem faço ideia de sugestões. Alguém sugere algo?

**Comment by ericdouglas** [comment]
Outra palavra que acho que não devemos traduzir :smile:

**Comment by ewertonorg** [comment]
Acho que não é legal traduzir termos técnicos. :)

**Comment by randsonjs** [comment]
Também

**Comment by gabrielfgularte** [comment]
Blz. Pode fechar também?

**Comment by ewertonorg** [comment]
:+1:
